//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sdp/SessionDescriptionImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSdpSessionDescriptionImpl")
#ifdef RESTRICT_AndroidGovNistJavaxSdpSessionDescriptionImpl
#define INCLUDE_ALL_AndroidGovNistJavaxSdpSessionDescriptionImpl 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSdpSessionDescriptionImpl 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSdpSessionDescriptionImpl

#if !defined (AndroidGovNistJavaxSdpSessionDescriptionImpl_) && (INCLUDE_ALL_AndroidGovNistJavaxSdpSessionDescriptionImpl || defined(INCLUDE_AndroidGovNistJavaxSdpSessionDescriptionImpl))
#define AndroidGovNistJavaxSdpSessionDescriptionImpl_

#define RESTRICT_AndroidJavaxSdpSessionDescription 1
#define INCLUDE_AndroidJavaxSdpSessionDescription 1
#include "android/javax/sdp/SessionDescription.h"

@class AndroidGovNistJavaxSdpFieldsConnectionField;
@class AndroidGovNistJavaxSdpFieldsInformationField;
@class AndroidGovNistJavaxSdpFieldsKeyField;
@class AndroidGovNistJavaxSdpFieldsOriginField;
@class AndroidGovNistJavaxSdpFieldsProtoVersionField;
@class AndroidGovNistJavaxSdpFieldsSDPField;
@class AndroidGovNistJavaxSdpFieldsSessionNameField;
@class AndroidGovNistJavaxSdpFieldsURIField;
@class JavaUtilVector;
@protocol AndroidJavaxSdpConnection;
@protocol AndroidJavaxSdpInfo;
@protocol AndroidJavaxSdpKey;
@protocol AndroidJavaxSdpOrigin;
@protocol AndroidJavaxSdpSessionName;
@protocol AndroidJavaxSdpURI;
@protocol AndroidJavaxSdpVersion;

@interface AndroidGovNistJavaxSdpSessionDescriptionImpl : NSObject < AndroidJavaxSdpSessionDescription > {
 @public
  AndroidGovNistJavaxSdpFieldsProtoVersionField *versionImpl_;
  AndroidGovNistJavaxSdpFieldsOriginField *originImpl_;
  AndroidGovNistJavaxSdpFieldsSessionNameField *sessionNameImpl_;
  AndroidGovNistJavaxSdpFieldsInformationField *infoImpl_;
  AndroidGovNistJavaxSdpFieldsURIField *uriImpl_;
  AndroidGovNistJavaxSdpFieldsConnectionField *connectionImpl_;
  AndroidGovNistJavaxSdpFieldsKeyField *keyImpl_;
  JavaUtilVector *timeDescriptions_;
  JavaUtilVector *mediaDescriptions_;
  JavaUtilVector *zoneAdjustments_;
  JavaUtilVector *emailList_;
  JavaUtilVector *phoneList_;
  JavaUtilVector *bandwidthList_;
  JavaUtilVector *attributesList_;
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithAndroidJavaxSdpSessionDescription:(id<AndroidJavaxSdpSessionDescription>)otherSessionDescription;

- (void)addFieldWithAndroidGovNistJavaxSdpFieldsSDPField:(AndroidGovNistJavaxSdpFieldsSDPField *)sdpField;

- (id)java_clone;

- (NSString *)getAttributeWithNSString:(NSString *)name;

- (JavaUtilVector *)getAttributesWithBoolean:(jboolean)create;

- (jint)getBandwidthWithNSString:(NSString *)name;

- (JavaUtilVector *)getBandwidthsWithBoolean:(jboolean)create;

- (id<AndroidJavaxSdpConnection>)getConnection;

- (JavaUtilVector *)getEmailsWithBoolean:(jboolean)create;

- (id<AndroidJavaxSdpInfo>)getInfo;

- (id<AndroidJavaxSdpKey>)getKey;

- (JavaUtilVector *)getMediaDescriptionsWithBoolean:(jboolean)create;

- (id<AndroidJavaxSdpOrigin>)getOrigin;

- (JavaUtilVector *)getPhonesWithBoolean:(jboolean)create;

- (id<AndroidJavaxSdpSessionName>)getSessionName;

- (JavaUtilVector *)getTimeDescriptionsWithBoolean:(jboolean)create;

- (id<AndroidJavaxSdpURI>)getURI;

- (id<AndroidJavaxSdpVersion>)getVersion;

- (JavaUtilVector *)getZoneAdjustmentsWithBoolean:(jboolean)create;

- (void)removeAttributeWithNSString:(NSString *)name;

- (void)removeBandwidthWithNSString:(NSString *)name;

- (void)setAttributeWithNSString:(NSString *)name
                    withNSString:(NSString *)value;

- (void)setAttributesWithJavaUtilVector:(JavaUtilVector *)attributes;

- (void)setBandwidthWithNSString:(NSString *)name
                         withInt:(jint)value;

- (void)setBandwidthsWithJavaUtilVector:(JavaUtilVector *)bandwidthList;

- (void)setConnectionWithAndroidJavaxSdpConnection:(id<AndroidJavaxSdpConnection>)conn;

- (void)setEmailsWithJavaUtilVector:(JavaUtilVector *)emails;

- (void)setInfoWithAndroidJavaxSdpInfo:(id<AndroidJavaxSdpInfo>)i;

- (void)setKeyWithAndroidJavaxSdpKey:(id<AndroidJavaxSdpKey>)key;

- (void)setMediaDescriptionsWithJavaUtilVector:(JavaUtilVector *)mediaDescriptions;

- (void)setOriginWithAndroidJavaxSdpOrigin:(id<AndroidJavaxSdpOrigin>)origin;

- (void)setPhonesWithJavaUtilVector:(JavaUtilVector *)phones;

- (void)setSessionNameWithAndroidJavaxSdpSessionName:(id<AndroidJavaxSdpSessionName>)sessionName;

- (void)setTimeDescriptionsWithJavaUtilVector:(JavaUtilVector *)times;

- (void)setURIWithAndroidJavaxSdpURI:(id<AndroidJavaxSdpURI>)uri;

- (void)setVersionWithAndroidJavaxSdpVersion:(id<AndroidJavaxSdpVersion>)v;

- (void)setZoneAdjustmentsWithJavaUtilVector:(JavaUtilVector *)zoneAdjustments;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSdpSessionDescriptionImpl)

J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSdpSessionDescriptionImpl, versionImpl_, AndroidGovNistJavaxSdpFieldsProtoVersionField *)
J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSdpSessionDescriptionImpl, originImpl_, AndroidGovNistJavaxSdpFieldsOriginField *)
J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSdpSessionDescriptionImpl, sessionNameImpl_, AndroidGovNistJavaxSdpFieldsSessionNameField *)
J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSdpSessionDescriptionImpl, infoImpl_, AndroidGovNistJavaxSdpFieldsInformationField *)
J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSdpSessionDescriptionImpl, uriImpl_, AndroidGovNistJavaxSdpFieldsURIField *)
J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSdpSessionDescriptionImpl, connectionImpl_, AndroidGovNistJavaxSdpFieldsConnectionField *)
J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSdpSessionDescriptionImpl, keyImpl_, AndroidGovNistJavaxSdpFieldsKeyField *)
J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSdpSessionDescriptionImpl, timeDescriptions_, JavaUtilVector *)
J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSdpSessionDescriptionImpl, mediaDescriptions_, JavaUtilVector *)
J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSdpSessionDescriptionImpl, zoneAdjustments_, JavaUtilVector *)
J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSdpSessionDescriptionImpl, emailList_, JavaUtilVector *)
J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSdpSessionDescriptionImpl, phoneList_, JavaUtilVector *)
J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSdpSessionDescriptionImpl, bandwidthList_, JavaUtilVector *)
J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSdpSessionDescriptionImpl, attributesList_, JavaUtilVector *)

FOUNDATION_EXPORT void AndroidGovNistJavaxSdpSessionDescriptionImpl_init(AndroidGovNistJavaxSdpSessionDescriptionImpl *self);

FOUNDATION_EXPORT AndroidGovNistJavaxSdpSessionDescriptionImpl *new_AndroidGovNistJavaxSdpSessionDescriptionImpl_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSdpSessionDescriptionImpl *create_AndroidGovNistJavaxSdpSessionDescriptionImpl_init();

FOUNDATION_EXPORT void AndroidGovNistJavaxSdpSessionDescriptionImpl_initWithAndroidJavaxSdpSessionDescription_(AndroidGovNistJavaxSdpSessionDescriptionImpl *self, id<AndroidJavaxSdpSessionDescription> otherSessionDescription);

FOUNDATION_EXPORT AndroidGovNistJavaxSdpSessionDescriptionImpl *new_AndroidGovNistJavaxSdpSessionDescriptionImpl_initWithAndroidJavaxSdpSessionDescription_(id<AndroidJavaxSdpSessionDescription> otherSessionDescription) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSdpSessionDescriptionImpl *create_AndroidGovNistJavaxSdpSessionDescriptionImpl_initWithAndroidJavaxSdpSessionDescription_(id<AndroidJavaxSdpSessionDescription> otherSessionDescription);

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSdpSessionDescriptionImpl)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSdpSessionDescriptionImpl")
