//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/stack/ClientAuthType.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "android/gov/nist/javax/sip/stack/ClientAuthType.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"

__attribute__((unused)) static void AndroidGovNistJavaxSipStackClientAuthType_initWithNSString_withInt_(AndroidGovNistJavaxSipStackClientAuthType *self, NSString *__name, jint __ordinal);

J2OBJC_INITIALIZED_DEFN(AndroidGovNistJavaxSipStackClientAuthType)

AndroidGovNistJavaxSipStackClientAuthType *AndroidGovNistJavaxSipStackClientAuthType_values_[5];

@implementation AndroidGovNistJavaxSipStackClientAuthType

+ (IOSObjectArray *)values {
  return AndroidGovNistJavaxSipStackClientAuthType_values();
}

+ (AndroidGovNistJavaxSipStackClientAuthType *)valueOfWithNSString:(NSString *)name {
  return AndroidGovNistJavaxSipStackClientAuthType_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "[LAndroidGovNistJavaxSipStackClientAuthType;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LAndroidGovNistJavaxSipStackClientAuthType;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(values);
  methods[1].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "Enabled", "LAndroidGovNistJavaxSipStackClientAuthType;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
    { "Disabled", "LAndroidGovNistJavaxSipStackClientAuthType;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
    { "DisabledAll", "LAndroidGovNistJavaxSipStackClientAuthType;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
    { "Want", "LAndroidGovNistJavaxSipStackClientAuthType;", .constantValue.asLong = 0, 0x4019, -1, 5, -1, -1 },
    { "Default", "LAndroidGovNistJavaxSipStackClientAuthType;", .constantValue.asLong = 0, 0x4019, -1, 6, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(AndroidGovNistJavaxSipStackClientAuthType, Enabled), &JreEnum(AndroidGovNistJavaxSipStackClientAuthType, Disabled), &JreEnum(AndroidGovNistJavaxSipStackClientAuthType, DisabledAll), &JreEnum(AndroidGovNistJavaxSipStackClientAuthType, Want), &JreEnum(AndroidGovNistJavaxSipStackClientAuthType, Default), "Ljava/lang/Enum<Landroid/gov/nist/javax/sip/stack/ClientAuthType;>;" };
  static const J2ObjcClassInfo _AndroidGovNistJavaxSipStackClientAuthType = { "ClientAuthType", "android.gov.nist.javax.sip.stack", ptrTable, methods, fields, 7, 0x4011, 2, 5, -1, -1, -1, 7, -1 };
  return &_AndroidGovNistJavaxSipStackClientAuthType;
}

+ (void)initialize {
  if (self == [AndroidGovNistJavaxSipStackClientAuthType class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 5 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    id names[] = {
      @"Enabled", @"Disabled", @"DisabledAll", @"Want", @"Default",
    };
    for (jint i = 0; i < 5; i++) {
      (AndroidGovNistJavaxSipStackClientAuthType_values_[i] = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
      AndroidGovNistJavaxSipStackClientAuthType_initWithNSString_withInt_(e, names[i], i);
    }
    J2OBJC_SET_INITIALIZED(AndroidGovNistJavaxSipStackClientAuthType)
  }
}

@end

void AndroidGovNistJavaxSipStackClientAuthType_initWithNSString_withInt_(AndroidGovNistJavaxSipStackClientAuthType *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

IOSObjectArray *AndroidGovNistJavaxSipStackClientAuthType_values() {
  AndroidGovNistJavaxSipStackClientAuthType_initialize();
  return [IOSObjectArray arrayWithObjects:AndroidGovNistJavaxSipStackClientAuthType_values_ count:5 type:AndroidGovNistJavaxSipStackClientAuthType_class_()];
}

AndroidGovNistJavaxSipStackClientAuthType *AndroidGovNistJavaxSipStackClientAuthType_valueOfWithNSString_(NSString *name) {
  AndroidGovNistJavaxSipStackClientAuthType_initialize();
  for (int i = 0; i < 5; i++) {
    AndroidGovNistJavaxSipStackClientAuthType *e = AndroidGovNistJavaxSipStackClientAuthType_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

AndroidGovNistJavaxSipStackClientAuthType *AndroidGovNistJavaxSipStackClientAuthType_fromOrdinal(NSUInteger ordinal) {
  AndroidGovNistJavaxSipStackClientAuthType_initialize();
  if (ordinal >= 5) {
    return nil;
  }
  return AndroidGovNistJavaxSipStackClientAuthType_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AndroidGovNistJavaxSipStackClientAuthType)
