//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/stack/CongestionControlMessageValve.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSipStackCongestionControlMessageValve")
#ifdef RESTRICT_AndroidGovNistJavaxSipStackCongestionControlMessageValve
#define INCLUDE_ALL_AndroidGovNistJavaxSipStackCongestionControlMessageValve 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSipStackCongestionControlMessageValve 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSipStackCongestionControlMessageValve

#if !defined (AndroidGovNistJavaxSipStackCongestionControlMessageValve_) && (INCLUDE_ALL_AndroidGovNistJavaxSipStackCongestionControlMessageValve || defined(INCLUDE_AndroidGovNistJavaxSipStackCongestionControlMessageValve))
#define AndroidGovNistJavaxSipStackCongestionControlMessageValve_

#define RESTRICT_AndroidGovNistJavaxSipStackSIPMessageValve 1
#define INCLUDE_AndroidGovNistJavaxSipStackSIPMessageValve 1
#include "android/gov/nist/javax/sip/stack/SIPMessageValve.h"

@class AndroidGovNistJavaxSipMessageSIPRequest;
@class AndroidGovNistJavaxSipSipStackImpl;
@class AndroidGovNistJavaxSipStackMessageChannel;
@protocol AndroidJavaxSipMessageResponse;
@protocol AndroidJavaxSipSipStack;

@interface AndroidGovNistJavaxSipStackCongestionControlMessageValve : NSObject < AndroidGovNistJavaxSipStackSIPMessageValve > {
 @public
  AndroidGovNistJavaxSipSipStackImpl *sipStack_;
  jint serverTransactionTableHighwaterMark_;
  jint dropResponseStatus_;
}

#pragma mark Public

- (instancetype)init;

- (void)destroy;

- (void)init__WithAndroidJavaxSipSipStack:(id<AndroidJavaxSipSipStack>)stack OBJC_METHOD_FAMILY_NONE;

- (jboolean)processRequestWithAndroidGovNistJavaxSipMessageSIPRequest:(AndroidGovNistJavaxSipMessageSIPRequest *)request
                        withAndroidGovNistJavaxSipStackMessageChannel:(AndroidGovNistJavaxSipStackMessageChannel *)messageChannel;

- (jboolean)processResponseWithAndroidJavaxSipMessageResponse:(id<AndroidJavaxSipMessageResponse>)response
                withAndroidGovNistJavaxSipStackMessageChannel:(AndroidGovNistJavaxSipStackMessageChannel *)messageChannel;

@end

J2OBJC_STATIC_INIT(AndroidGovNistJavaxSipStackCongestionControlMessageValve)

J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSipStackCongestionControlMessageValve, sipStack_, AndroidGovNistJavaxSipSipStackImpl *)

FOUNDATION_EXPORT void AndroidGovNistJavaxSipStackCongestionControlMessageValve_init(AndroidGovNistJavaxSipStackCongestionControlMessageValve *self);

FOUNDATION_EXPORT AndroidGovNistJavaxSipStackCongestionControlMessageValve *new_AndroidGovNistJavaxSipStackCongestionControlMessageValve_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSipStackCongestionControlMessageValve *create_AndroidGovNistJavaxSipStackCongestionControlMessageValve_init();

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSipStackCongestionControlMessageValve)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSipStackCongestionControlMessageValve")
