//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/stack/DatagramQueuedMessageDispatch.java
//

#include "J2ObjC_source.h"
#include "android/gov/nist/javax/sip/stack/DatagramQueuedMessageDispatch.h"
#include "java/net/DatagramPacket.h"

@implementation AndroidGovNistJavaxSipStackDatagramQueuedMessageDispatch

- (instancetype)initWithJavaNetDatagramPacket:(JavaNetDatagramPacket *)packet
                                     withLong:(jlong)time {
  AndroidGovNistJavaxSipStackDatagramQueuedMessageDispatch_initWithJavaNetDatagramPacket_withLong_(self, packet, time);
  return self;
}

- (jlong)getReceptionTime {
  return time_;
}

- (void)run {
}

- (void)dealloc {
  RELEASE_(packet_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "J", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithJavaNetDatagramPacket:withLong:);
  methods[1].selector = @selector(getReceptionTime);
  methods[2].selector = @selector(run);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "packet_", "LJavaNetDatagramPacket;", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
    { "time_", "J", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LJavaNetDatagramPacket;J" };
  static const J2ObjcClassInfo _AndroidGovNistJavaxSipStackDatagramQueuedMessageDispatch = { "DatagramQueuedMessageDispatch", "android.gov.nist.javax.sip.stack", ptrTable, methods, fields, 7, 0x1, 3, 2, -1, -1, -1, -1, -1 };
  return &_AndroidGovNistJavaxSipStackDatagramQueuedMessageDispatch;
}

@end

void AndroidGovNistJavaxSipStackDatagramQueuedMessageDispatch_initWithJavaNetDatagramPacket_withLong_(AndroidGovNistJavaxSipStackDatagramQueuedMessageDispatch *self, JavaNetDatagramPacket *packet, jlong time) {
  NSObject_init(self);
  self->time_ = time;
  JreStrongAssign(&self->packet_, packet);
}

AndroidGovNistJavaxSipStackDatagramQueuedMessageDispatch *new_AndroidGovNistJavaxSipStackDatagramQueuedMessageDispatch_initWithJavaNetDatagramPacket_withLong_(JavaNetDatagramPacket *packet, jlong time) {
  J2OBJC_NEW_IMPL(AndroidGovNistJavaxSipStackDatagramQueuedMessageDispatch, initWithJavaNetDatagramPacket_withLong_, packet, time)
}

AndroidGovNistJavaxSipStackDatagramQueuedMessageDispatch *create_AndroidGovNistJavaxSipStackDatagramQueuedMessageDispatch_initWithJavaNetDatagramPacket_withLong_(JavaNetDatagramPacket *packet, jlong time) {
  J2OBJC_CREATE_IMPL(AndroidGovNistJavaxSipStackDatagramQueuedMessageDispatch, initWithJavaNetDatagramPacket_withLong_, packet, time)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AndroidGovNistJavaxSipStackDatagramQueuedMessageDispatch)
