//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/stack/DefaultMessageLogFactory.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSipStackDefaultMessageLogFactory")
#ifdef RESTRICT_AndroidGovNistJavaxSipStackDefaultMessageLogFactory
#define INCLUDE_ALL_AndroidGovNistJavaxSipStackDefaultMessageLogFactory 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSipStackDefaultMessageLogFactory 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSipStackDefaultMessageLogFactory

#if !defined (AndroidGovNistJavaxSipStackDefaultMessageLogFactory_) && (INCLUDE_ALL_AndroidGovNistJavaxSipStackDefaultMessageLogFactory || defined(INCLUDE_AndroidGovNistJavaxSipStackDefaultMessageLogFactory))
#define AndroidGovNistJavaxSipStackDefaultMessageLogFactory_

#define RESTRICT_AndroidGovNistJavaxSipLogRecordFactory 1
#define INCLUDE_AndroidGovNistJavaxSipLogRecordFactory 1
#include "android/gov/nist/javax/sip/LogRecordFactory.h"

@protocol AndroidGovNistJavaxSipLogRecord;

@interface AndroidGovNistJavaxSipStackDefaultMessageLogFactory : NSObject < AndroidGovNistJavaxSipLogRecordFactory >

#pragma mark Public

- (instancetype)init;

- (id<AndroidGovNistJavaxSipLogRecord>)createLogRecordWithNSString:(NSString *)message
                                                      withNSString:(NSString *)source
                                                      withNSString:(NSString *)destination
                                                          withLong:(jlong)timeStamp
                                                       withBoolean:(jboolean)isSender
                                                      withNSString:(NSString *)firstLine
                                                      withNSString:(NSString *)tid
                                                      withNSString:(NSString *)callId
                                                          withLong:(jlong)timestampVal;

- (id<AndroidGovNistJavaxSipLogRecord>)createLogRecordWithNSString:(NSString *)message
                                                      withNSString:(NSString *)source
                                                      withNSString:(NSString *)destination
                                                      withNSString:(NSString *)timeStamp
                                                       withBoolean:(jboolean)isSender
                                                      withNSString:(NSString *)firstLine
                                                      withNSString:(NSString *)tid
                                                      withNSString:(NSString *)callId
                                                          withLong:(jlong)tsHeaderValue;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSipStackDefaultMessageLogFactory)

FOUNDATION_EXPORT void AndroidGovNistJavaxSipStackDefaultMessageLogFactory_init(AndroidGovNistJavaxSipStackDefaultMessageLogFactory *self);

FOUNDATION_EXPORT AndroidGovNistJavaxSipStackDefaultMessageLogFactory *new_AndroidGovNistJavaxSipStackDefaultMessageLogFactory_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSipStackDefaultMessageLogFactory *create_AndroidGovNistJavaxSipStackDefaultMessageLogFactory_init();

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSipStackDefaultMessageLogFactory)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSipStackDefaultMessageLogFactory")
