//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/stack/ServerRequestInterface.java
//

#include "J2ObjC_source.h"
#include "android/gov/nist/javax/sip/stack/ServerRequestInterface.h"

@interface AndroidGovNistJavaxSipStackServerRequestInterface : NSObject

@end

@implementation AndroidGovNistJavaxSipStackServerRequestInterface

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(processRequestWithAndroidGovNistJavaxSipMessageSIPRequest:withAndroidGovNistJavaxSipStackMessageChannel:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "processRequest", "LAndroidGovNistJavaxSipMessageSIPRequest;LAndroidGovNistJavaxSipStackMessageChannel;" };
  static const J2ObjcClassInfo _AndroidGovNistJavaxSipStackServerRequestInterface = { "ServerRequestInterface", "android.gov.nist.javax.sip.stack", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_AndroidGovNistJavaxSipStackServerRequestInterface;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(AndroidGovNistJavaxSipStackServerRequestInterface)
