//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/stack/SIPEventInterceptor.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSipStackSIPEventInterceptor")
#ifdef RESTRICT_AndroidGovNistJavaxSipStackSIPEventInterceptor
#define INCLUDE_ALL_AndroidGovNistJavaxSipStackSIPEventInterceptor 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSipStackSIPEventInterceptor 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSipStackSIPEventInterceptor

#if !defined (AndroidGovNistJavaxSipStackSIPEventInterceptor_) && (INCLUDE_ALL_AndroidGovNistJavaxSipStackSIPEventInterceptor || defined(INCLUDE_AndroidGovNistJavaxSipStackSIPEventInterceptor))
#define AndroidGovNistJavaxSipStackSIPEventInterceptor_

@protocol AndroidJavaxSipMessageMessage;
@protocol AndroidJavaxSipSipStack;

@protocol AndroidGovNistJavaxSipStackSIPEventInterceptor < JavaObject >

- (void)beforeMessageWithAndroidJavaxSipMessageMessage:(id<AndroidJavaxSipMessageMessage>)message;

- (void)afterMessageWithAndroidJavaxSipMessageMessage:(id<AndroidJavaxSipMessageMessage>)message;

- (void)init__WithAndroidJavaxSipSipStack:(id<AndroidJavaxSipSipStack>)stack OBJC_METHOD_FAMILY_NONE;

- (void)destroy;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSipStackSIPEventInterceptor)

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSipStackSIPEventInterceptor)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSipStackSIPEventInterceptor")
