#!/bin/zsh

CLASSPATH="$(for i in lib/*.jar ; do echo -n $i: ; done)src"

#Using j2objc stable 1.3.1
#USED_J2OBJC_VERSION="/Users/guilhermesgb/workspace/jfl/ios/j2objc-1.3.1/j2objc"

#Using the 564997a30d5b8f6e96fc248a97279abad5a77760 version on the master branch, it's on my $PATH
USED_J2OBJC_VERSION="j2objc"

echo "Obtaining Java sources list..."
find . \! -name ".java" | grep \\.java > java_sources.list
echo "Preparing to translate to iOS-ready Objective-C sources..."
mkdir -p j2objc_gen/src
echo "Translating using classpath: `echo $CLASSPATH`."
$USED_J2OBJC_VERSION -d j2objc_gen/src -sourcepath "$CLASSPATH" --no-package-directories --build-closure -g @java_sources.list
#-d j2objc_gen/src -sourcepath "$CLASSPATH" --no-package-directories --build-closure -g @java_sources.list
echo "Done translating."
rm java_sources.list
