//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sdp/parser/PhoneFieldParser.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSdpParserPhoneFieldParser")
#ifdef RESTRICT_AndroidGovNistJavaxSdpParserPhoneFieldParser
#define INCLUDE_ALL_AndroidGovNistJavaxSdpParserPhoneFieldParser 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSdpParserPhoneFieldParser 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSdpParserPhoneFieldParser

#if !defined (AndroidGovNistJavaxSdpParserPhoneFieldParser_) && (INCLUDE_ALL_AndroidGovNistJavaxSdpParserPhoneFieldParser || defined(INCLUDE_AndroidGovNistJavaxSdpParserPhoneFieldParser))
#define AndroidGovNistJavaxSdpParserPhoneFieldParser_

#define RESTRICT_AndroidGovNistJavaxSdpParserSDPParser 1
#define INCLUDE_AndroidGovNistJavaxSdpParserSDPParser 1
#include "android/gov/nist/javax/sdp/parser/SDPParser.h"

@class AndroidGovNistJavaxSdpFieldsPhoneField;
@class AndroidGovNistJavaxSdpFieldsSDPField;

@interface AndroidGovNistJavaxSdpParserPhoneFieldParser : AndroidGovNistJavaxSdpParserSDPParser

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)phoneField;

- (NSString *)getDisplayNameWithNSString:(NSString *)rest;

- (NSString *)getPhoneNumberWithNSString:(NSString *)rest;

- (AndroidGovNistJavaxSdpFieldsSDPField *)parse;

- (AndroidGovNistJavaxSdpFieldsPhoneField *)phoneField;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSdpParserPhoneFieldParser)

FOUNDATION_EXPORT void AndroidGovNistJavaxSdpParserPhoneFieldParser_initWithNSString_(AndroidGovNistJavaxSdpParserPhoneFieldParser *self, NSString *phoneField);

FOUNDATION_EXPORT AndroidGovNistJavaxSdpParserPhoneFieldParser *new_AndroidGovNistJavaxSdpParserPhoneFieldParser_initWithNSString_(NSString *phoneField) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSdpParserPhoneFieldParser *create_AndroidGovNistJavaxSdpParserPhoneFieldParser_initWithNSString_(NSString *phoneField);

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSdpParserPhoneFieldParser)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSdpParserPhoneFieldParser")
