//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sdp/parser/URIFieldParser.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSdpParserURIFieldParser")
#ifdef RESTRICT_AndroidGovNistJavaxSdpParserURIFieldParser
#define INCLUDE_ALL_AndroidGovNistJavaxSdpParserURIFieldParser 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSdpParserURIFieldParser 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSdpParserURIFieldParser

#if !defined (AndroidGovNistJavaxSdpParserURIFieldParser_) && (INCLUDE_ALL_AndroidGovNistJavaxSdpParserURIFieldParser || defined(INCLUDE_AndroidGovNistJavaxSdpParserURIFieldParser))
#define AndroidGovNistJavaxSdpParserURIFieldParser_

#define RESTRICT_AndroidGovNistJavaxSdpParserSDPParser 1
#define INCLUDE_AndroidGovNistJavaxSdpParserSDPParser 1
#include "android/gov/nist/javax/sdp/parser/SDPParser.h"

@class AndroidGovNistJavaxSdpFieldsSDPField;
@class AndroidGovNistJavaxSdpFieldsURIField;

@interface AndroidGovNistJavaxSdpParserURIFieldParser : AndroidGovNistJavaxSdpParserSDPParser

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)uriField;

- (AndroidGovNistJavaxSdpFieldsSDPField *)parse;

- (AndroidGovNistJavaxSdpFieldsURIField *)uriField;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSdpParserURIFieldParser)

FOUNDATION_EXPORT void AndroidGovNistJavaxSdpParserURIFieldParser_initWithNSString_(AndroidGovNistJavaxSdpParserURIFieldParser *self, NSString *uriField);

FOUNDATION_EXPORT AndroidGovNistJavaxSdpParserURIFieldParser *new_AndroidGovNistJavaxSdpParserURIFieldParser_initWithNSString_(NSString *uriField) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSdpParserURIFieldParser *create_AndroidGovNistJavaxSdpParserURIFieldParser_initWithNSString_(NSString *uriField);

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSdpParserURIFieldParser)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSdpParserURIFieldParser")
