//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/core/net/NetworkLayer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistCoreNetNetworkLayer")
#ifdef RESTRICT_AndroidGovNistCoreNetNetworkLayer
#define INCLUDE_ALL_AndroidGovNistCoreNetNetworkLayer 0
#else
#define INCLUDE_ALL_AndroidGovNistCoreNetNetworkLayer 1
#endif
#undef RESTRICT_AndroidGovNistCoreNetNetworkLayer

#if !defined (AndroidGovNistCoreNetNetworkLayer_) && (INCLUDE_ALL_AndroidGovNistCoreNetNetworkLayer || defined(INCLUDE_AndroidGovNistCoreNetNetworkLayer))
#define AndroidGovNistCoreNetNetworkLayer_

@class AndroidGovNistJavaxSipSipStackImpl;
@class JavaNetDatagramSocket;
@class JavaNetInetAddress;
@class JavaNetServerSocket;
@class JavaNetSocket;
@class JavaxNetSslSSLServerSocket;
@class JavaxNetSslSSLSocket;

@protocol AndroidGovNistCoreNetNetworkLayer < JavaObject >

- (JavaNetServerSocket *)createServerSocketWithInt:(jint)port
                                           withInt:(jint)backlog
                            withJavaNetInetAddress:(JavaNetInetAddress *)bindAddress;

- (JavaxNetSslSSLServerSocket *)createSSLServerSocketWithInt:(jint)port
                                                     withInt:(jint)backlog
                                      withJavaNetInetAddress:(JavaNetInetAddress *)bindAddress;

- (JavaNetSocket *)createSocketWithJavaNetInetAddress:(JavaNetInetAddress *)address
                                              withInt:(jint)port;

- (JavaNetSocket *)createSocketWithJavaNetInetAddress:(JavaNetInetAddress *)address
                                              withInt:(jint)port
                               withJavaNetInetAddress:(JavaNetInetAddress *)localAddress;

- (JavaNetSocket *)createSocketWithJavaNetInetAddress:(JavaNetInetAddress *)address
                                              withInt:(jint)port
                               withJavaNetInetAddress:(JavaNetInetAddress *)myAddress
                                              withInt:(jint)myPort;

- (JavaxNetSslSSLSocket *)createSSLSocketWithJavaNetInetAddress:(JavaNetInetAddress *)address
                                                        withInt:(jint)port;

- (JavaxNetSslSSLSocket *)createSSLSocketWithJavaNetInetAddress:(JavaNetInetAddress *)address
                                                        withInt:(jint)port
                                         withJavaNetInetAddress:(JavaNetInetAddress *)localAddress;

- (JavaNetDatagramSocket *)createDatagramSocket;

- (JavaNetDatagramSocket *)createDatagramSocketWithInt:(jint)port
                                withJavaNetInetAddress:(JavaNetInetAddress *)laddr;

- (void)setSipStackWithAndroidGovNistJavaxSipSipStackImpl:(AndroidGovNistJavaxSipSipStackImpl *)sipStackImpl;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistCoreNetNetworkLayer)

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistCoreNetNetworkLayer)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistCoreNetNetworkLayer")
