//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/parser/CallIDParser.java
//

#include "J2ObjC_source.h"
#include "android/gov/nist/core/LexerCore.h"
#include "android/gov/nist/core/ParserCore.h"
#include "android/gov/nist/core/Token.h"
#include "android/gov/nist/javax/sip/header/CallID.h"
#include "android/gov/nist/javax/sip/header/SIPHeader.h"
#include "android/gov/nist/javax/sip/parser/CallIDParser.h"
#include "android/gov/nist/javax/sip/parser/HeaderParser.h"
#include "android/gov/nist/javax/sip/parser/Lexer.h"
#include "android/gov/nist/javax/sip/parser/TokenTypes.h"

@implementation AndroidGovNistJavaxSipParserCallIDParser

- (instancetype)initWithNSString:(NSString *)callID {
  AndroidGovNistJavaxSipParserCallIDParser_initWithNSString_(self, callID);
  return self;
}

- (instancetype)initWithAndroidGovNistJavaxSipParserLexer:(AndroidGovNistJavaxSipParserLexer *)lexer {
  AndroidGovNistJavaxSipParserCallIDParser_initWithAndroidGovNistJavaxSipParserLexer_(self, lexer);
  return self;
}

- (AndroidGovNistJavaxSipHeaderSIPHeader *)parse {
  if (JreLoadStatic(AndroidGovNistCoreParserCore, debug)) [self dbg_enterWithNSString:@"parse"];
  @try {
    [((AndroidGovNistCoreLexerCore *) nil_chk(self->lexer_)) matchWithInt:AndroidGovNistJavaxSipParserTokenTypes_CALL_ID];
    [((AndroidGovNistCoreLexerCore *) nil_chk(self->lexer_)) SPorHT];
    [((AndroidGovNistCoreLexerCore *) nil_chk(self->lexer_)) matchWithInt:':'];
    [((AndroidGovNistCoreLexerCore *) nil_chk(self->lexer_)) SPorHT];
    AndroidGovNistJavaxSipHeaderCallID *callID = create_AndroidGovNistJavaxSipHeaderCallID_init();
    [((AndroidGovNistCoreLexerCore *) nil_chk(self->lexer_)) SPorHT];
    NSString *rest = [((AndroidGovNistCoreLexerCore *) nil_chk(lexer_)) getRest];
    [callID setCallIdWithNSString:[((NSString *) nil_chk(rest)) java_trim]];
    return callID;
  }
  @finally {
    if (JreLoadStatic(AndroidGovNistCoreParserCore, debug)) [self dbg_leaveWithNSString:@"parse"];
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x4, -1, 1, -1, -1, -1, -1 },
    { NULL, "LAndroidGovNistJavaxSipHeaderSIPHeader;", 0x1, -1, -1, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithNSString:);
  methods[1].selector = @selector(initWithAndroidGovNistJavaxSipParserLexer:);
  methods[2].selector = @selector(parse);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LNSString;", "LAndroidGovNistJavaxSipParserLexer;", "LJavaTextParseException;" };
  static const J2ObjcClassInfo _AndroidGovNistJavaxSipParserCallIDParser = { "CallIDParser", "android.gov.nist.javax.sip.parser", ptrTable, methods, NULL, 7, 0x1, 3, 0, -1, -1, -1, -1, -1 };
  return &_AndroidGovNistJavaxSipParserCallIDParser;
}

@end

void AndroidGovNistJavaxSipParserCallIDParser_initWithNSString_(AndroidGovNistJavaxSipParserCallIDParser *self, NSString *callID) {
  AndroidGovNistJavaxSipParserHeaderParser_initWithNSString_(self, callID);
}

AndroidGovNistJavaxSipParserCallIDParser *new_AndroidGovNistJavaxSipParserCallIDParser_initWithNSString_(NSString *callID) {
  J2OBJC_NEW_IMPL(AndroidGovNistJavaxSipParserCallIDParser, initWithNSString_, callID)
}

AndroidGovNistJavaxSipParserCallIDParser *create_AndroidGovNistJavaxSipParserCallIDParser_initWithNSString_(NSString *callID) {
  J2OBJC_CREATE_IMPL(AndroidGovNistJavaxSipParserCallIDParser, initWithNSString_, callID)
}

void AndroidGovNistJavaxSipParserCallIDParser_initWithAndroidGovNistJavaxSipParserLexer_(AndroidGovNistJavaxSipParserCallIDParser *self, AndroidGovNistJavaxSipParserLexer *lexer) {
  AndroidGovNistJavaxSipParserHeaderParser_initWithAndroidGovNistJavaxSipParserLexer_(self, lexer);
}

AndroidGovNistJavaxSipParserCallIDParser *new_AndroidGovNistJavaxSipParserCallIDParser_initWithAndroidGovNistJavaxSipParserLexer_(AndroidGovNistJavaxSipParserLexer *lexer) {
  J2OBJC_NEW_IMPL(AndroidGovNistJavaxSipParserCallIDParser, initWithAndroidGovNistJavaxSipParserLexer_, lexer)
}

AndroidGovNistJavaxSipParserCallIDParser *create_AndroidGovNistJavaxSipParserCallIDParser_initWithAndroidGovNistJavaxSipParserLexer_(AndroidGovNistJavaxSipParserLexer *lexer) {
  J2OBJC_CREATE_IMPL(AndroidGovNistJavaxSipParserCallIDParser, initWithAndroidGovNistJavaxSipParserLexer_, lexer)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AndroidGovNistJavaxSipParserCallIDParser)
