//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/clientauthutils/DigestServerAuthenticationHelper.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper")
#ifdef RESTRICT_AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper
#define INCLUDE_ALL_AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper

#if !defined (AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper_) && (INCLUDE_ALL_AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper || defined(INCLUDE_AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper))
#define AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper_

@class IOSByteArray;
@protocol AndroidJavaxSipHeaderHeaderFactory;
@protocol AndroidJavaxSipMessageRequest;
@protocol AndroidJavaxSipMessageResponse;

@interface AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper : NSObject

#pragma mark Public

- (instancetype)init;

- (jboolean)doAuthenticateHashedPasswordWithAndroidJavaxSipMessageRequest:(id<AndroidJavaxSipMessageRequest>)request
                                                             withNSString:(NSString *)hashedPassword;

- (jboolean)doAuthenticatePlainTextPasswordWithAndroidJavaxSipMessageRequest:(id<AndroidJavaxSipMessageRequest>)request
                                                                withNSString:(NSString *)pass;

- (void)generateChallengeWithAndroidJavaxSipHeaderHeaderFactory:(id<AndroidJavaxSipHeaderHeaderFactory>)headerFactory
                             withAndroidJavaxSipMessageResponse:(id<AndroidJavaxSipMessageResponse>)response
                                                   withNSString:(NSString *)realm;

+ (NSString *)toHexStringWithByteArray:(IOSByteArray *)b;

@end

J2OBJC_STATIC_INIT(AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper)

inline NSString *AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper_get_DEFAULT_ALGORITHM();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper_DEFAULT_ALGORITHM;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper, DEFAULT_ALGORITHM, NSString *)

inline NSString *AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper_get_DEFAULT_SCHEME();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper_DEFAULT_SCHEME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper, DEFAULT_SCHEME, NSString *)

FOUNDATION_EXPORT void AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper_init(AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper *self);

FOUNDATION_EXPORT AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper *new_AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper *create_AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper_init();

FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper_toHexStringWithByteArray_(IOSByteArray *b);

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSipClientauthutilsDigestServerAuthenticationHelper")
