//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/org/opentelecoms/javax/sdp/NistSdpFactory.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidOrgOpentelecomsJavaxSdpNistSdpFactory")
#ifdef RESTRICT_AndroidOrgOpentelecomsJavaxSdpNistSdpFactory
#define INCLUDE_ALL_AndroidOrgOpentelecomsJavaxSdpNistSdpFactory 0
#else
#define INCLUDE_ALL_AndroidOrgOpentelecomsJavaxSdpNistSdpFactory 1
#endif
#undef RESTRICT_AndroidOrgOpentelecomsJavaxSdpNistSdpFactory

#if !defined (AndroidOrgOpentelecomsJavaxSdpNistSdpFactory_) && (INCLUDE_ALL_AndroidOrgOpentelecomsJavaxSdpNistSdpFactory || defined(INCLUDE_AndroidOrgOpentelecomsJavaxSdpNistSdpFactory))
#define AndroidOrgOpentelecomsJavaxSdpNistSdpFactory_

#define RESTRICT_AndroidJavaxSdpSdpFactory 1
#define INCLUDE_AndroidJavaxSdpSdpFactory 1
#include "android/javax/sdp/SdpFactory.h"

@class IOSIntArray;
@class IOSObjectArray;
@class JavaNetURL;
@class JavaUtilDate;
@class JavaUtilVector;
@protocol AndroidJavaxSdpAttribute;
@protocol AndroidJavaxSdpBandWidth;
@protocol AndroidJavaxSdpConnection;
@protocol AndroidJavaxSdpEMail;
@protocol AndroidJavaxSdpInfo;
@protocol AndroidJavaxSdpKey;
@protocol AndroidJavaxSdpMedia;
@protocol AndroidJavaxSdpMediaDescription;
@protocol AndroidJavaxSdpOrigin;
@protocol AndroidJavaxSdpPhone;
@protocol AndroidJavaxSdpRepeatTime;
@protocol AndroidJavaxSdpSessionDescription;
@protocol AndroidJavaxSdpSessionName;
@protocol AndroidJavaxSdpTime;
@protocol AndroidJavaxSdpTimeDescription;
@protocol AndroidJavaxSdpTimeZoneAdjustment;
@protocol AndroidJavaxSdpURI;
@protocol AndroidJavaxSdpVersion;

@interface AndroidOrgOpentelecomsJavaxSdpNistSdpFactory : NSObject < AndroidJavaxSdpSdpFactory >

#pragma mark Public

- (instancetype)init;

- (id<AndroidJavaxSdpAttribute>)createAttributeWithNSString:(NSString *)name
                                               withNSString:(NSString *)value;

- (id<AndroidJavaxSdpBandWidth>)createBandwidthWithNSString:(NSString *)modifier
                                                    withInt:(jint)value;

- (id<AndroidJavaxSdpConnection>)createConnectionWithNSString:(NSString *)addr;

- (id<AndroidJavaxSdpConnection>)createConnectionWithNSString:(NSString *)addr
                                                      withInt:(jint)ttl
                                                      withInt:(jint)numAddrs;

- (id<AndroidJavaxSdpConnection>)createConnectionWithNSString:(NSString *)netType
                                                 withNSString:(NSString *)addrType
                                                 withNSString:(NSString *)addr;

- (id<AndroidJavaxSdpConnection>)createConnectionWithNSString:(NSString *)netType
                                                 withNSString:(NSString *)addrType
                                                 withNSString:(NSString *)addr
                                                      withInt:(jint)ttl
                                                      withInt:(jint)numAddrs;

- (id<AndroidJavaxSdpEMail>)createEMailWithNSString:(NSString *)value;

- (id<AndroidJavaxSdpInfo>)createInfoWithNSString:(NSString *)value;

- (id<AndroidJavaxSdpKey>)createKeyWithNSString:(NSString *)method
                                   withNSString:(NSString *)key;

- (id<AndroidJavaxSdpMedia>)createMediaWithNSString:(NSString *)media
                                            withInt:(jint)port
                                            withInt:(jint)numPorts
                                       withNSString:(NSString *)transport
                                 withJavaUtilVector:(JavaUtilVector *)staticRtpAvpTypes;

- (id<AndroidJavaxSdpMediaDescription>)createMediaDescriptionWithNSString:(NSString *)media
                                                                  withInt:(jint)port
                                                                  withInt:(jint)numPorts
                                                             withNSString:(NSString *)transport
                                                             withIntArray:(IOSIntArray *)staticRtpAvpTypes;

- (id<AndroidJavaxSdpMediaDescription>)createMediaDescriptionWithNSString:(NSString *)media
                                                                  withInt:(jint)port
                                                                  withInt:(jint)numPorts
                                                             withNSString:(NSString *)transport
                                                        withNSStringArray:(IOSObjectArray *)formats;

- (id<AndroidJavaxSdpOrigin>)createOriginWithNSString:(NSString *)userName
                                             withLong:(jlong)sessionId
                                             withLong:(jlong)sessionVersion
                                         withNSString:(NSString *)networkType
                                         withNSString:(NSString *)addrType
                                         withNSString:(NSString *)address;

- (id<AndroidJavaxSdpOrigin>)createOriginWithNSString:(NSString *)userName
                                         withNSString:(NSString *)address;

- (id<AndroidJavaxSdpPhone>)createPhoneWithNSString:(NSString *)value;

- (id<AndroidJavaxSdpRepeatTime>)createRepeatTimeWithInt:(jint)repeatInterval
                                                 withInt:(jint)activeDuration
                                            withIntArray:(IOSIntArray *)offsets;

- (id<AndroidJavaxSdpSessionDescription>)createSessionDescription;

- (id<AndroidJavaxSdpSessionDescription>)createSessionDescriptionWithNSString:(NSString *)s;

- (id<AndroidJavaxSdpSessionName>)createSessionNameWithNSString:(NSString *)name;

- (id<AndroidJavaxSdpTime>)createTime;

- (id<AndroidJavaxSdpTime>)createTimeWithJavaUtilDate:(JavaUtilDate *)start
                                     withJavaUtilDate:(JavaUtilDate *)stop;

- (id<AndroidJavaxSdpTimeDescription>)createTimeDescription;

- (id<AndroidJavaxSdpTimeDescription>)createTimeDescriptionWithJavaUtilDate:(JavaUtilDate *)start
                                                           withJavaUtilDate:(JavaUtilDate *)stop;

- (id<AndroidJavaxSdpTimeDescription>)createTimeDescriptionWithAndroidJavaxSdpTime:(id<AndroidJavaxSdpTime>)t;

- (id<AndroidJavaxSdpTimeZoneAdjustment>)createTimeZoneAdjustmentWithJavaUtilDate:(JavaUtilDate *)d
                                                                          withInt:(jint)offset;

- (id<AndroidJavaxSdpURI>)createURIWithJavaNetURL:(JavaNetURL *)value;

- (id<AndroidJavaxSdpVersion>)createVersionWithInt:(jint)value;

- (NSString *)formatMulticastAddressWithNSString:(NSString *)addr
                                         withInt:(jint)ttl
                                         withInt:(jint)numAddrs;

- (JavaUtilDate *)getDateFromNtpWithLong:(jlong)ntpTime;

- (jlong)getNtpTimeWithJavaUtilDate:(JavaUtilDate *)d;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidOrgOpentelecomsJavaxSdpNistSdpFactory)

FOUNDATION_EXPORT void AndroidOrgOpentelecomsJavaxSdpNistSdpFactory_init(AndroidOrgOpentelecomsJavaxSdpNistSdpFactory *self);

FOUNDATION_EXPORT AndroidOrgOpentelecomsJavaxSdpNistSdpFactory *new_AndroidOrgOpentelecomsJavaxSdpNistSdpFactory_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidOrgOpentelecomsJavaxSdpNistSdpFactory *create_AndroidOrgOpentelecomsJavaxSdpNistSdpFactory_init();

J2OBJC_TYPE_LITERAL_HEADER(AndroidOrgOpentelecomsJavaxSdpNistSdpFactory)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidOrgOpentelecomsJavaxSdpNistSdpFactory")
