//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/header/AcceptEncoding.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderAcceptEncoding")
#ifdef RESTRICT_AndroidGovNistJavaxSipHeaderAcceptEncoding
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderAcceptEncoding 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderAcceptEncoding 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSipHeaderAcceptEncoding

#if !defined (AndroidGovNistJavaxSipHeaderAcceptEncoding_) && (INCLUDE_ALL_AndroidGovNistJavaxSipHeaderAcceptEncoding || defined(INCLUDE_AndroidGovNistJavaxSipHeaderAcceptEncoding))
#define AndroidGovNistJavaxSipHeaderAcceptEncoding_

#define RESTRICT_AndroidGovNistJavaxSipHeaderParametersHeader 1
#define INCLUDE_AndroidGovNistJavaxSipHeaderParametersHeader 1
#include "android/gov/nist/javax/sip/header/ParametersHeader.h"

#define RESTRICT_AndroidJavaxSipHeaderAcceptEncodingHeader 1
#define INCLUDE_AndroidJavaxSipHeaderAcceptEncodingHeader 1
#include "android/javax/sip/header/AcceptEncodingHeader.h"

@class JavaLangStringBuilder;

@interface AndroidGovNistJavaxSipHeaderAcceptEncoding : AndroidGovNistJavaxSipHeaderParametersHeader < AndroidJavaxSipHeaderAcceptEncodingHeader > {
 @public
  NSString *contentCoding_;
}

#pragma mark Public

- (instancetype)init;

- (NSString *)getEncoding;

- (jfloat)getQValue;

- (void)setEncodingWithNSString:(NSString *)encoding;

- (void)setQValueWithFloat:(jfloat)q;

#pragma mark Protected

- (NSString *)encodeBody;

- (JavaLangStringBuilder *)encodeBodyWithJavaLangStringBuilder:(JavaLangStringBuilder *)buffer;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSipHeaderAcceptEncoding)

J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSipHeaderAcceptEncoding, contentCoding_, NSString *)

FOUNDATION_EXPORT void AndroidGovNistJavaxSipHeaderAcceptEncoding_init(AndroidGovNistJavaxSipHeaderAcceptEncoding *self);

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderAcceptEncoding *new_AndroidGovNistJavaxSipHeaderAcceptEncoding_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderAcceptEncoding *create_AndroidGovNistJavaxSipHeaderAcceptEncoding_init();

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSipHeaderAcceptEncoding)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderAcceptEncoding")
