//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/header/AddressParametersHeader.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderAddressParametersHeader")
#ifdef RESTRICT_AndroidGovNistJavaxSipHeaderAddressParametersHeader
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderAddressParametersHeader 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderAddressParametersHeader 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSipHeaderAddressParametersHeader

#if !defined (AndroidGovNistJavaxSipHeaderAddressParametersHeader_) && (INCLUDE_ALL_AndroidGovNistJavaxSipHeaderAddressParametersHeader || defined(INCLUDE_AndroidGovNistJavaxSipHeaderAddressParametersHeader))
#define AndroidGovNistJavaxSipHeaderAddressParametersHeader_

#define RESTRICT_AndroidGovNistJavaxSipHeaderParametersHeader 1
#define INCLUDE_AndroidGovNistJavaxSipHeaderParametersHeader 1
#include "android/gov/nist/javax/sip/header/ParametersHeader.h"

#define RESTRICT_AndroidJavaxSipHeaderParameters 1
#define INCLUDE_AndroidJavaxSipHeaderParameters 1
#include "android/javax/sip/header/Parameters.h"

@class AndroidGovNistJavaxSipAddressAddressImpl;
@protocol AndroidJavaxSipAddressAddress;

@interface AndroidGovNistJavaxSipHeaderAddressParametersHeader : AndroidGovNistJavaxSipHeaderParametersHeader < AndroidJavaxSipHeaderParameters > {
 @public
  AndroidGovNistJavaxSipAddressAddressImpl *address_;
}

#pragma mark Public

- (id)java_clone;

- (jboolean)isEqual:(id)other;

- (id<AndroidJavaxSipAddressAddress>)getAddress;

- (void)setAddressWithAndroidJavaxSipAddressAddress:(id<AndroidJavaxSipAddressAddress>)address;

#pragma mark Protected

- (instancetype)initWithNSString:(NSString *)name;

- (instancetype)initWithNSString:(NSString *)name
                     withBoolean:(jboolean)sync;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSipHeaderAddressParametersHeader)

J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSipHeaderAddressParametersHeader, address_, AndroidGovNistJavaxSipAddressAddressImpl *)

FOUNDATION_EXPORT void AndroidGovNistJavaxSipHeaderAddressParametersHeader_initWithNSString_(AndroidGovNistJavaxSipHeaderAddressParametersHeader *self, NSString *name);

FOUNDATION_EXPORT void AndroidGovNistJavaxSipHeaderAddressParametersHeader_initWithNSString_withBoolean_(AndroidGovNistJavaxSipHeaderAddressParametersHeader *self, NSString *name, jboolean sync);

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSipHeaderAddressParametersHeader)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderAddressParametersHeader")
