//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/header/Expires.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderExpires")
#ifdef RESTRICT_AndroidGovNistJavaxSipHeaderExpires
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderExpires 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderExpires 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSipHeaderExpires

#if !defined (AndroidGovNistJavaxSipHeaderExpires_) && (INCLUDE_ALL_AndroidGovNistJavaxSipHeaderExpires || defined(INCLUDE_AndroidGovNistJavaxSipHeaderExpires))
#define AndroidGovNistJavaxSipHeaderExpires_

#define RESTRICT_AndroidGovNistJavaxSipHeaderSIPHeader 1
#define INCLUDE_AndroidGovNistJavaxSipHeaderSIPHeader 1
#include "android/gov/nist/javax/sip/header/SIPHeader.h"

#define RESTRICT_AndroidJavaxSipHeaderExpiresHeader 1
#define INCLUDE_AndroidJavaxSipHeaderExpiresHeader 1
#include "android/javax/sip/header/ExpiresHeader.h"

@class JavaLangStringBuilder;

@interface AndroidGovNistJavaxSipHeaderExpires : AndroidGovNistJavaxSipHeaderSIPHeader < AndroidJavaxSipHeaderExpiresHeader > {
 @public
  jint expires_;
}

#pragma mark Public

- (instancetype)init;

- (NSString *)encodeBody;

- (jint)getExpires;

- (void)setExpiresWithInt:(jint)expires;

#pragma mark Protected

- (JavaLangStringBuilder *)encodeBodyWithJavaLangStringBuilder:(JavaLangStringBuilder *)buffer;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSipHeaderExpires)

FOUNDATION_EXPORT void AndroidGovNistJavaxSipHeaderExpires_init(AndroidGovNistJavaxSipHeaderExpires *self);

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderExpires *new_AndroidGovNistJavaxSipHeaderExpires_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderExpires *create_AndroidGovNistJavaxSipHeaderExpires_init();

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSipHeaderExpires)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderExpires")
