//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/header/ExtensionHeaderList.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "android/gov/nist/javax/sip/header/ExtensionHeaderImpl.h"
#include "android/gov/nist/javax/sip/header/ExtensionHeaderList.h"
#include "android/gov/nist/javax/sip/header/SIPHeaderList.h"
#include "java/lang/StringBuilder.h"
#include "java/util/List.h"
#include "java/util/ListIterator.h"

#pragma clang diagnostic ignored "-Wincomplete-implementation"

inline jlong AndroidGovNistJavaxSipHeaderExtensionHeaderList_get_serialVersionUID();
#define AndroidGovNistJavaxSipHeaderExtensionHeaderList_serialVersionUID 4681326807149890197LL
J2OBJC_STATIC_FIELD_CONSTANT(AndroidGovNistJavaxSipHeaderExtensionHeaderList, serialVersionUID, jlong)

@implementation AndroidGovNistJavaxSipHeaderExtensionHeaderList

- (id)java_clone {
  AndroidGovNistJavaxSipHeaderExtensionHeaderList *retval = create_AndroidGovNistJavaxSipHeaderExtensionHeaderList_initWithNSString_(headerName_);
  [retval clonehlistWithJavaUtilList:self->hlist_];
  return retval;
}

- (instancetype)initWithNSString:(NSString *)hName {
  AndroidGovNistJavaxSipHeaderExtensionHeaderList_initWithNSString_(self, hName);
  return self;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  AndroidGovNistJavaxSipHeaderExtensionHeaderList_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (NSString *)encode {
  JavaLangStringBuilder *retval = create_JavaLangStringBuilder_init();
  id<JavaUtilListIterator> it = [self listIterator];
  while ([((id<JavaUtilListIterator>) nil_chk(it)) hasNext]) {
    AndroidGovNistJavaxSipHeaderExtensionHeaderImpl *eh = [it next];
    [retval appendWithNSString:[((AndroidGovNistJavaxSipHeaderExtensionHeaderImpl *) nil_chk(eh)) encode]];
  }
  return [retval description];
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf, len);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSObject;", 0x1, 0, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(java_clone);
  methods[1].selector = @selector(initWithNSString:);
  methods[2].selector = @selector(init);
  methods[3].selector = @selector(encode);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = AndroidGovNistJavaxSipHeaderExtensionHeaderList_serialVersionUID, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "clone", "LNSString;", "Landroid/gov/nist/javax/sip/header/SIPHeaderList<Landroid/gov/nist/javax/sip/header/ExtensionHeaderImpl;>;" };
  static const J2ObjcClassInfo _AndroidGovNistJavaxSipHeaderExtensionHeaderList = { "ExtensionHeaderList", "android.gov.nist.javax.sip.header", ptrTable, methods, fields, 7, 0x1, 4, 1, -1, -1, -1, 2, -1 };
  return &_AndroidGovNistJavaxSipHeaderExtensionHeaderList;
}

@end

void AndroidGovNistJavaxSipHeaderExtensionHeaderList_initWithNSString_(AndroidGovNistJavaxSipHeaderExtensionHeaderList *self, NSString *hName) {
  AndroidGovNistJavaxSipHeaderSIPHeaderList_initWithIOSClass_withNSString_(self, AndroidGovNistJavaxSipHeaderExtensionHeaderImpl_class_(), hName);
}

AndroidGovNistJavaxSipHeaderExtensionHeaderList *new_AndroidGovNistJavaxSipHeaderExtensionHeaderList_initWithNSString_(NSString *hName) {
  J2OBJC_NEW_IMPL(AndroidGovNistJavaxSipHeaderExtensionHeaderList, initWithNSString_, hName)
}

AndroidGovNistJavaxSipHeaderExtensionHeaderList *create_AndroidGovNistJavaxSipHeaderExtensionHeaderList_initWithNSString_(NSString *hName) {
  J2OBJC_CREATE_IMPL(AndroidGovNistJavaxSipHeaderExtensionHeaderList, initWithNSString_, hName)
}

void AndroidGovNistJavaxSipHeaderExtensionHeaderList_init(AndroidGovNistJavaxSipHeaderExtensionHeaderList *self) {
  AndroidGovNistJavaxSipHeaderSIPHeaderList_initWithIOSClass_withNSString_(self, AndroidGovNistJavaxSipHeaderExtensionHeaderImpl_class_(), nil);
}

AndroidGovNistJavaxSipHeaderExtensionHeaderList *new_AndroidGovNistJavaxSipHeaderExtensionHeaderList_init() {
  J2OBJC_NEW_IMPL(AndroidGovNistJavaxSipHeaderExtensionHeaderList, init)
}

AndroidGovNistJavaxSipHeaderExtensionHeaderList *create_AndroidGovNistJavaxSipHeaderExtensionHeaderList_init() {
  J2OBJC_CREATE_IMPL(AndroidGovNistJavaxSipHeaderExtensionHeaderList, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AndroidGovNistJavaxSipHeaderExtensionHeaderList)
