//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/header/Organization.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderOrganization")
#ifdef RESTRICT_AndroidGovNistJavaxSipHeaderOrganization
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderOrganization 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderOrganization 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSipHeaderOrganization

#if !defined (AndroidGovNistJavaxSipHeaderOrganization_) && (INCLUDE_ALL_AndroidGovNistJavaxSipHeaderOrganization || defined(INCLUDE_AndroidGovNistJavaxSipHeaderOrganization))
#define AndroidGovNistJavaxSipHeaderOrganization_

#define RESTRICT_AndroidGovNistJavaxSipHeaderSIPHeader 1
#define INCLUDE_AndroidGovNistJavaxSipHeaderSIPHeader 1
#include "android/gov/nist/javax/sip/header/SIPHeader.h"

#define RESTRICT_AndroidJavaxSipHeaderOrganizationHeader 1
#define INCLUDE_AndroidJavaxSipHeaderOrganizationHeader 1
#include "android/javax/sip/header/OrganizationHeader.h"

@class JavaLangStringBuilder;

@interface AndroidGovNistJavaxSipHeaderOrganization : AndroidGovNistJavaxSipHeaderSIPHeader < AndroidJavaxSipHeaderOrganizationHeader > {
 @public
  NSString *organization_;
}

#pragma mark Public

- (instancetype)init;

- (JavaLangStringBuilder *)encodeBodyWithJavaLangStringBuilder:(JavaLangStringBuilder *)buffer;

- (NSString *)getOrganization;

- (void)setOrganizationWithNSString:(NSString *)o;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSipHeaderOrganization)

J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSipHeaderOrganization, organization_, NSString *)

FOUNDATION_EXPORT void AndroidGovNistJavaxSipHeaderOrganization_init(AndroidGovNistJavaxSipHeaderOrganization *self);

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderOrganization *new_AndroidGovNistJavaxSipHeaderOrganization_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderOrganization *create_AndroidGovNistJavaxSipHeaderOrganization_init();

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSipHeaderOrganization)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderOrganization")
