//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/header/ParametersHeader.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderParametersHeader")
#ifdef RESTRICT_AndroidGovNistJavaxSipHeaderParametersHeader
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderParametersHeader 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderParametersHeader 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSipHeaderParametersHeader

#if !defined (AndroidGovNistJavaxSipHeaderParametersHeader_) && (INCLUDE_ALL_AndroidGovNistJavaxSipHeaderParametersHeader || defined(INCLUDE_AndroidGovNistJavaxSipHeaderParametersHeader))
#define AndroidGovNistJavaxSipHeaderParametersHeader_

#define RESTRICT_AndroidGovNistJavaxSipHeaderSIPHeader 1
#define INCLUDE_AndroidGovNistJavaxSipHeaderSIPHeader 1
#include "android/gov/nist/javax/sip/header/SIPHeader.h"

#define RESTRICT_AndroidJavaxSipHeaderParameters 1
#define INCLUDE_AndroidJavaxSipHeaderParameters 1
#include "android/javax/sip/header/Parameters.h"

#define RESTRICT_AndroidGovNistJavaxSipHeaderParametersExt 1
#define INCLUDE_AndroidGovNistJavaxSipHeaderParametersExt 1
#include "android/gov/nist/javax/sip/header/ParametersExt.h"

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@class AndroidGovNistCoreDuplicateNameValueList;
@class AndroidGovNistCoreNameValue;
@class AndroidGovNistCoreNameValueList;
@class AndroidGovNistJavaxSipAddressGenericURI;
@class JavaLangStringBuilder;
@protocol JavaUtilIterator;

@interface AndroidGovNistJavaxSipHeaderParametersHeader : AndroidGovNistJavaxSipHeaderSIPHeader < AndroidJavaxSipHeaderParameters, AndroidGovNistJavaxSipHeaderParametersExt, JavaIoSerializable > {
 @public
  AndroidGovNistCoreNameValueList *parameters_;
  AndroidGovNistCoreDuplicateNameValueList *duplicates_;
}

#pragma mark Public

- (id)java_clone;

- (NSString *)getMultiParameterWithNSString:(NSString *)name;

- (id<JavaUtilIterator>)getMultiParameterNames;

- (AndroidGovNistCoreDuplicateNameValueList *)getMultiParameters;

- (id)getMultiParameterValueWithNSString:(NSString *)name;

- (AndroidGovNistCoreNameValue *)getNameValueWithNSString:(NSString *)parameterName;

- (NSString *)getParameterWithNSString:(NSString *)name;

- (NSString *)getParameterWithNSString:(NSString *)name
                           withBoolean:(jboolean)stripQuotes;

- (id<JavaUtilIterator>)getParameterNames;

- (AndroidGovNistCoreNameValueList *)getParameters;

- (id)getParameterValueWithNSString:(NSString *)name;

- (jboolean)hasMultiParameterWithNSString:(NSString *)parameterName;

- (jboolean)hasMultiParameters;

- (jboolean)hasParameterWithNSString:(NSString *)parameterName;

- (jboolean)hasParameters;

- (void)removeMultiParameterWithNSString:(NSString *)name;

- (void)removeMultiParameters;

- (void)removeParameterWithNSString:(NSString *)name;

- (void)removeParameters;

- (void)setMultiParameterWithAndroidGovNistCoreNameValue:(AndroidGovNistCoreNameValue *)nameValue;

- (void)setMultiParameterWithNSString:(NSString *)name
                         withNSString:(NSString *)value;

- (void)setParameterWithAndroidGovNistCoreNameValue:(AndroidGovNistCoreNameValue *)nameValue;

- (void)setParameterWithNSString:(NSString *)name
                    withNSString:(NSString *)value;

- (void)setParametersWithAndroidGovNistCoreNameValueList:(AndroidGovNistCoreNameValueList *)parameters;

- (void)setQuotedParameterWithNSString:(NSString *)name
                          withNSString:(NSString *)value;

#pragma mark Protected

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)hdrName;

- (instancetype)initWithNSString:(NSString *)hdrName
                     withBoolean:(jboolean)sync;

- (JavaLangStringBuilder *)encodeBodyWithJavaLangStringBuilder:(JavaLangStringBuilder *)buffer;

- (jboolean)equalParametersWithAndroidJavaxSipHeaderParameters:(id<AndroidJavaxSipHeaderParameters>)other;

- (jboolean)getParameterAsBooleanWithNSString:(NSString *)parameterName;

- (jfloat)getParameterAsFloatWithNSString:(NSString *)parameterName;

- (jint)getParameterAsHexIntWithNSString:(NSString *)parameterName;

- (jint)getParameterAsIntWithNSString:(NSString *)parameterName;

- (jlong)getParameterAsLongWithNSString:(NSString *)parameterName;

- (AndroidGovNistJavaxSipAddressGenericURI *)getParameterAsURIWithNSString:(NSString *)parameterName;

- (void)setParameterWithNSString:(NSString *)name
                     withBoolean:(jboolean)value;

- (void)setParameterWithNSString:(NSString *)name
                       withFloat:(jfloat)value;

- (void)setParameterWithNSString:(NSString *)name
                         withInt:(jint)value;

- (void)setParameterWithNSString:(NSString *)name
                          withId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSipHeaderParametersHeader)

J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSipHeaderParametersHeader, parameters_, AndroidGovNistCoreNameValueList *)
J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSipHeaderParametersHeader, duplicates_, AndroidGovNistCoreDuplicateNameValueList *)

FOUNDATION_EXPORT void AndroidGovNistJavaxSipHeaderParametersHeader_init(AndroidGovNistJavaxSipHeaderParametersHeader *self);

FOUNDATION_EXPORT void AndroidGovNistJavaxSipHeaderParametersHeader_initWithNSString_(AndroidGovNistJavaxSipHeaderParametersHeader *self, NSString *hdrName);

FOUNDATION_EXPORT void AndroidGovNistJavaxSipHeaderParametersHeader_initWithNSString_withBoolean_(AndroidGovNistJavaxSipHeaderParametersHeader *self, NSString *hdrName, jboolean sync);

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSipHeaderParametersHeader)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderParametersHeader")
