//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/header/ProxyRequire.java
//

#include "J2ObjC_source.h"
#include "android/gov/nist/javax/sip/header/ProxyRequire.h"
#include "android/gov/nist/javax/sip/header/SIPHeader.h"
#include "android/gov/nist/javax/sip/header/SIPHeaderNames.h"
#include "java/lang/NullPointerException.h"
#include "java/lang/StringBuilder.h"

inline jlong AndroidGovNistJavaxSipHeaderProxyRequire_get_serialVersionUID();
#define AndroidGovNistJavaxSipHeaderProxyRequire_serialVersionUID -3269274234851067893LL
J2OBJC_STATIC_FIELD_CONSTANT(AndroidGovNistJavaxSipHeaderProxyRequire, serialVersionUID, jlong)

@implementation AndroidGovNistJavaxSipHeaderProxyRequire

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  AndroidGovNistJavaxSipHeaderProxyRequire_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)s {
  AndroidGovNistJavaxSipHeaderProxyRequire_initWithNSString_(self, s);
  return self;
}

- (JavaLangStringBuilder *)encodeBodyWithJavaLangStringBuilder:(JavaLangStringBuilder *)buffer {
  return [((JavaLangStringBuilder *) nil_chk(buffer)) appendWithNSString:optionTag_];
}

- (void)setOptionTagWithNSString:(NSString *)optionTag {
  if (optionTag == nil) @throw create_JavaLangNullPointerException_initWithNSString_(@"JAIN-SIP Exception, ProxyRequire, setOptionTag(), the optionTag parameter is null");
  JreStrongAssign(&self->optionTag_, optionTag);
}

- (NSString *)getOptionTag {
  return optionTag_;
}

- (void)dealloc {
  RELEASE_(optionTag_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LJavaLangStringBuilder;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 0, 4, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithNSString:);
  methods[2].selector = @selector(encodeBodyWithJavaLangStringBuilder:);
  methods[3].selector = @selector(setOptionTagWithNSString:);
  methods[4].selector = @selector(getOptionTag);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = AndroidGovNistJavaxSipHeaderProxyRequire_serialVersionUID, 0x1a, -1, -1, -1, -1 },
    { "optionTag_", "LNSString;", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;", "encodeBody", "LJavaLangStringBuilder;", "setOptionTag", "LJavaTextParseException;" };
  static const J2ObjcClassInfo _AndroidGovNistJavaxSipHeaderProxyRequire = { "ProxyRequire", "android.gov.nist.javax.sip.header", ptrTable, methods, fields, 7, 0x1, 5, 2, -1, -1, -1, -1, -1 };
  return &_AndroidGovNistJavaxSipHeaderProxyRequire;
}

@end

void AndroidGovNistJavaxSipHeaderProxyRequire_init(AndroidGovNistJavaxSipHeaderProxyRequire *self) {
  AndroidGovNistJavaxSipHeaderSIPHeader_initWithNSString_(self, AndroidGovNistJavaxSipHeaderSIPHeaderNames_PROXY_REQUIRE);
}

AndroidGovNistJavaxSipHeaderProxyRequire *new_AndroidGovNistJavaxSipHeaderProxyRequire_init() {
  J2OBJC_NEW_IMPL(AndroidGovNistJavaxSipHeaderProxyRequire, init)
}

AndroidGovNistJavaxSipHeaderProxyRequire *create_AndroidGovNistJavaxSipHeaderProxyRequire_init() {
  J2OBJC_CREATE_IMPL(AndroidGovNistJavaxSipHeaderProxyRequire, init)
}

void AndroidGovNistJavaxSipHeaderProxyRequire_initWithNSString_(AndroidGovNistJavaxSipHeaderProxyRequire *self, NSString *s) {
  AndroidGovNistJavaxSipHeaderSIPHeader_initWithNSString_(self, AndroidGovNistJavaxSipHeaderSIPHeaderNames_PROXY_REQUIRE);
  JreStrongAssign(&self->optionTag_, s);
}

AndroidGovNistJavaxSipHeaderProxyRequire *new_AndroidGovNistJavaxSipHeaderProxyRequire_initWithNSString_(NSString *s) {
  J2OBJC_NEW_IMPL(AndroidGovNistJavaxSipHeaderProxyRequire, initWithNSString_, s)
}

AndroidGovNistJavaxSipHeaderProxyRequire *create_AndroidGovNistJavaxSipHeaderProxyRequire_initWithNSString_(NSString *s) {
  J2OBJC_CREATE_IMPL(AndroidGovNistJavaxSipHeaderProxyRequire, initWithNSString_, s)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AndroidGovNistJavaxSipHeaderProxyRequire)
