//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/header/SIPHeaderNames.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderSIPHeaderNames")
#ifdef RESTRICT_AndroidGovNistJavaxSipHeaderSIPHeaderNames
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderSIPHeaderNames 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderSIPHeaderNames 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSipHeaderSIPHeaderNames

#if !defined (AndroidGovNistJavaxSipHeaderSIPHeaderNames_) && (INCLUDE_ALL_AndroidGovNistJavaxSipHeaderSIPHeaderNames || defined(INCLUDE_AndroidGovNistJavaxSipHeaderSIPHeaderNames))
#define AndroidGovNistJavaxSipHeaderSIPHeaderNames_

@protocol AndroidGovNistJavaxSipHeaderSIPHeaderNames < JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSipHeaderSIPHeaderNames)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_MIN_EXPIRES();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_MIN_EXPIRES;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, MIN_EXPIRES, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_ERROR_INFO();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_ERROR_INFO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, ERROR_INFO, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_MIME_VERSION();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_MIME_VERSION;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, MIME_VERSION, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_IN_REPLY_TO();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_IN_REPLY_TO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, IN_REPLY_TO, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_ALLOW();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_ALLOW;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, ALLOW, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_CONTENT_LANGUAGE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_CONTENT_LANGUAGE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, CONTENT_LANGUAGE, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_CALL_INFO();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_CALL_INFO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, CALL_INFO, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_CSEQ();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_CSEQ;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, CSEQ, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_ALERT_INFO();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_ALERT_INFO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, ALERT_INFO, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_ACCEPT_ENCODING();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_ACCEPT_ENCODING;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, ACCEPT_ENCODING, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_ACCEPT();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_ACCEPT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, ACCEPT, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_ACCEPT_LANGUAGE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_ACCEPT_LANGUAGE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, ACCEPT_LANGUAGE, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_RECORD_ROUTE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_RECORD_ROUTE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, RECORD_ROUTE, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_TIMESTAMP();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_TIMESTAMP;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, TIMESTAMP, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_TO();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_TO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, TO, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_VIA();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_VIA;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, VIA, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_FROM();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_FROM;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, FROM, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_CALL_ID();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_CALL_ID;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, CALL_ID, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_AUTHORIZATION();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_AUTHORIZATION;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, AUTHORIZATION, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_PROXY_AUTHENTICATE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_PROXY_AUTHENTICATE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, PROXY_AUTHENTICATE, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_SERVER();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_SERVER;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, SERVER, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_UNSUPPORTED();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_UNSUPPORTED;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, UNSUPPORTED, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_RETRY_AFTER();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_RETRY_AFTER;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, RETRY_AFTER, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_CONTENT_TYPE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_CONTENT_TYPE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, CONTENT_TYPE, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_CONTENT_ENCODING();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_CONTENT_ENCODING;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, CONTENT_ENCODING, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_CONTENT_LENGTH();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_CONTENT_LENGTH;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, CONTENT_LENGTH, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_ROUTE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_ROUTE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, ROUTE, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_CONTACT();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_CONTACT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, CONTACT, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_WWW_AUTHENTICATE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_WWW_AUTHENTICATE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, WWW_AUTHENTICATE, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_MAX_FORWARDS();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_MAX_FORWARDS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, MAX_FORWARDS, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_ORGANIZATION();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_ORGANIZATION;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, ORGANIZATION, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_PROXY_AUTHORIZATION();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_PROXY_AUTHORIZATION;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, PROXY_AUTHORIZATION, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_PROXY_REQUIRE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_PROXY_REQUIRE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, PROXY_REQUIRE, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_REQUIRE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_REQUIRE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, REQUIRE, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_CONTENT_DISPOSITION();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_CONTENT_DISPOSITION;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, CONTENT_DISPOSITION, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_SUBJECT();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_SUBJECT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, SUBJECT, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_USER_AGENT();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_USER_AGENT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, USER_AGENT, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_WARNING();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_WARNING;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, WARNING, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_PRIORITY();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_PRIORITY;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, PRIORITY, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_DATE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_DATE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, DATE, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_EXPIRES();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_EXPIRES;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, EXPIRES, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_SUPPORTED();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_SUPPORTED;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, SUPPORTED, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_AUTHENTICATION_INFO();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_AUTHENTICATION_INFO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, AUTHENTICATION_INFO, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_REPLY_TO();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_REPLY_TO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, REPLY_TO, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_RACK();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_RACK;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, RACK, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_RSEQ();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_RSEQ;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, RSEQ, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_REASON();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_REASON;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, REASON, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_SUBSCRIPTION_STATE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_SUBSCRIPTION_STATE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, SUBSCRIPTION_STATE, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_EVENT();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_EVENT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, EVENT, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_ALLOW_EVENTS();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_ALLOW_EVENTS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, ALLOW_EVENTS, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_SIP_ETAG();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_SIP_ETAG;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, SIP_ETAG, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_SIP_IF_MATCH();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_SIP_IF_MATCH;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, SIP_IF_MATCH, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_REFERRED_BY();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_REFERRED_BY;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, REFERRED_BY, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_SESSION_EXPIRES();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_SESSION_EXPIRES;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, SESSION_EXPIRES, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_MIN_SE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_MIN_SE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, MIN_SE, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_REPLACES();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_REPLACES;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, REPLACES, NSString *)

inline NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_get_JOIN();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidGovNistJavaxSipHeaderSIPHeaderNames_JOIN;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidGovNistJavaxSipHeaderSIPHeaderNames, JOIN, NSString *)

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSipHeaderSIPHeaderNames)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderSIPHeaderNames")
