//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/header/SIPHeader.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderSIPHeader")
#ifdef RESTRICT_AndroidGovNistJavaxSipHeaderSIPHeader
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderSIPHeader 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderSIPHeader 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSipHeaderSIPHeader

#if !defined (AndroidGovNistJavaxSipHeaderSIPHeader_) && (INCLUDE_ALL_AndroidGovNistJavaxSipHeaderSIPHeader || defined(INCLUDE_AndroidGovNistJavaxSipHeaderSIPHeader))
#define AndroidGovNistJavaxSipHeaderSIPHeader_

#define RESTRICT_AndroidGovNistJavaxSipHeaderSIPObject 1
#define INCLUDE_AndroidGovNistJavaxSipHeaderSIPObject 1
#include "android/gov/nist/javax/sip/header/SIPObject.h"

#define RESTRICT_AndroidGovNistJavaxSipHeaderSIPHeaderNames 1
#define INCLUDE_AndroidGovNistJavaxSipHeaderSIPHeaderNames 1
#include "android/gov/nist/javax/sip/header/SIPHeaderNames.h"

#define RESTRICT_AndroidJavaxSipHeaderHeader 1
#define INCLUDE_AndroidJavaxSipHeaderHeader 1
#include "android/javax/sip/header/Header.h"

#define RESTRICT_AndroidGovNistJavaxSipHeaderHeaderExt 1
#define INCLUDE_AndroidGovNistJavaxSipHeaderHeaderExt 1
#include "android/gov/nist/javax/sip/header/HeaderExt.h"

@class JavaLangStringBuilder;

@interface AndroidGovNistJavaxSipHeaderSIPHeader : AndroidGovNistJavaxSipHeaderSIPObject < AndroidGovNistJavaxSipHeaderSIPHeaderNames, AndroidJavaxSipHeaderHeader, AndroidGovNistJavaxSipHeaderHeaderExt > {
 @public
  NSString *headerName_;
}

#pragma mark Public

- (instancetype)init;

- (NSString *)encode;

- (JavaLangStringBuilder *)encodeWithJavaLangStringBuilder:(JavaLangStringBuilder *)buffer;

- (NSString *)getHeaderName;

- (NSString *)getHeaderValue;

- (NSString *)getName;

- (NSString *)getValue;

- (NSUInteger)hash;

- (jboolean)isHeaderList;

- (void)setHeaderNameWithNSString:(NSString *)hdrname;

- (NSString *)description;

#pragma mark Protected

- (instancetype)initWithNSString:(NSString *)hname;

- (JavaLangStringBuilder *)encodeBodyWithJavaLangStringBuilder:(JavaLangStringBuilder *)buffer;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSipHeaderSIPHeader)

J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSipHeaderSIPHeader, headerName_, NSString *)

FOUNDATION_EXPORT void AndroidGovNistJavaxSipHeaderSIPHeader_initWithNSString_(AndroidGovNistJavaxSipHeaderSIPHeader *self, NSString *hname);

FOUNDATION_EXPORT void AndroidGovNistJavaxSipHeaderSIPHeader_init(AndroidGovNistJavaxSipHeaderSIPHeader *self);

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSipHeaderSIPHeader)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderSIPHeader")
