//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:lib/slf4j-api-1.7.13-sources.jar!org/slf4j/impl/StaticLoggerBinder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_StaticLoggerBinder")
#ifdef RESTRICT_StaticLoggerBinder
#define INCLUDE_ALL_StaticLoggerBinder 0
#else
#define INCLUDE_ALL_StaticLoggerBinder 1
#endif
#undef RESTRICT_StaticLoggerBinder

#if !defined (OrgSlf4jImplStaticLoggerBinder_) && (INCLUDE_ALL_StaticLoggerBinder || defined(INCLUDE_OrgSlf4jImplStaticLoggerBinder))
#define OrgSlf4jImplStaticLoggerBinder_

@protocol OrgSlf4jILoggerFactory;

@interface OrgSlf4jImplStaticLoggerBinder : NSObject

#pragma mark Public

- (id<OrgSlf4jILoggerFactory>)getLoggerFactory;

- (NSString *)getLoggerFactoryClassStr;

+ (OrgSlf4jImplStaticLoggerBinder *)getSingleton;

@end

J2OBJC_STATIC_INIT(OrgSlf4jImplStaticLoggerBinder)

inline NSString *OrgSlf4jImplStaticLoggerBinder_get_REQUESTED_API_VERSION();
inline NSString *OrgSlf4jImplStaticLoggerBinder_set_REQUESTED_API_VERSION(NSString *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgSlf4jImplStaticLoggerBinder_REQUESTED_API_VERSION;
J2OBJC_STATIC_FIELD_OBJ(OrgSlf4jImplStaticLoggerBinder, REQUESTED_API_VERSION, NSString *)

FOUNDATION_EXPORT OrgSlf4jImplStaticLoggerBinder *OrgSlf4jImplStaticLoggerBinder_getSingleton();

J2OBJC_TYPE_LITERAL_HEADER(OrgSlf4jImplStaticLoggerBinder)

#endif

#pragma pop_macro("INCLUDE_ALL_StaticLoggerBinder")
