//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:lib/slf4j-api-1.7.13-sources.jar!org/slf4j/helpers/SubstituteLogger.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SubstituteLogger")
#ifdef RESTRICT_SubstituteLogger
#define INCLUDE_ALL_SubstituteLogger 0
#else
#define INCLUDE_ALL_SubstituteLogger 1
#endif
#undef RESTRICT_SubstituteLogger

#if !defined (OrgSlf4jHelpersSubstituteLogger_) && (INCLUDE_ALL_SubstituteLogger || defined(INCLUDE_OrgSlf4jHelpersSubstituteLogger))
#define OrgSlf4jHelpersSubstituteLogger_

#define RESTRICT_Logger 1
#define INCLUDE_OrgSlf4jLogger 1
#include "Logger.h"

@class IOSObjectArray;
@protocol OrgSlf4jMarker;

@interface OrgSlf4jHelpersSubstituteLogger : NSObject < OrgSlf4jLogger >

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)name;

- (void)debugWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                   withNSString:(NSString *)msg;

- (void)debugWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                   withNSString:(NSString *)format
                         withId:(id)arg;

- (void)debugWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                   withNSString:(NSString *)format
              withNSObjectArray:(IOSObjectArray *)arguments;

- (void)debugWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                   withNSString:(NSString *)format
                         withId:(id)arg1
                         withId:(id)arg2;

- (void)debugWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                   withNSString:(NSString *)msg
                withNSException:(NSException *)t;

- (void)debugWithNSString:(NSString *)msg;

- (void)debugWithNSString:(NSString *)format
                   withId:(id)arg;

- (void)debugWithNSString:(NSString *)format
        withNSObjectArray:(IOSObjectArray *)arguments;

- (void)debugWithNSString:(NSString *)format
                   withId:(id)arg1
                   withId:(id)arg2;

- (void)debugWithNSString:(NSString *)msg
          withNSException:(NSException *)t;

- (jboolean)isEqual:(id)o;

- (void)errorWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                   withNSString:(NSString *)msg;

- (void)errorWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                   withNSString:(NSString *)format
                         withId:(id)arg;

- (void)errorWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                   withNSString:(NSString *)format
              withNSObjectArray:(IOSObjectArray *)arguments;

- (void)errorWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                   withNSString:(NSString *)format
                         withId:(id)arg1
                         withId:(id)arg2;

- (void)errorWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                   withNSString:(NSString *)msg
                withNSException:(NSException *)t;

- (void)errorWithNSString:(NSString *)msg;

- (void)errorWithNSString:(NSString *)format
                   withId:(id)arg;

- (void)errorWithNSString:(NSString *)format
        withNSObjectArray:(IOSObjectArray *)arguments;

- (void)errorWithNSString:(NSString *)format
                   withId:(id)arg1
                   withId:(id)arg2;

- (void)errorWithNSString:(NSString *)msg
          withNSException:(NSException *)t;

- (NSString *)getName;

- (NSUInteger)hash;

- (void)infoWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                  withNSString:(NSString *)msg;

- (void)infoWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                  withNSString:(NSString *)format
                        withId:(id)arg;

- (void)infoWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                  withNSString:(NSString *)format
             withNSObjectArray:(IOSObjectArray *)arguments;

- (void)infoWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                  withNSString:(NSString *)format
                        withId:(id)arg1
                        withId:(id)arg2;

- (void)infoWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                  withNSString:(NSString *)msg
               withNSException:(NSException *)t;

- (void)infoWithNSString:(NSString *)msg;

- (void)infoWithNSString:(NSString *)format
                  withId:(id)arg;

- (void)infoWithNSString:(NSString *)format
       withNSObjectArray:(IOSObjectArray *)arguments;

- (void)infoWithNSString:(NSString *)format
                  withId:(id)arg1
                  withId:(id)arg2;

- (void)infoWithNSString:(NSString *)msg
         withNSException:(NSException *)t;

- (jboolean)isDebugEnabled;

- (jboolean)isDebugEnabledWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker;

- (jboolean)isErrorEnabled;

- (jboolean)isErrorEnabledWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker;

- (jboolean)isInfoEnabled;

- (jboolean)isInfoEnabledWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker;

- (jboolean)isTraceEnabled;

- (jboolean)isTraceEnabledWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker;

- (jboolean)isWarnEnabled;

- (jboolean)isWarnEnabledWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker;

- (void)setDelegateWithOrgSlf4jLogger:(id<OrgSlf4jLogger>)delegate;

- (void)traceWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                   withNSString:(NSString *)msg;

- (void)traceWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                   withNSString:(NSString *)format
                         withId:(id)arg;

- (void)traceWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                   withNSString:(NSString *)format
              withNSObjectArray:(IOSObjectArray *)arguments;

- (void)traceWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                   withNSString:(NSString *)format
                         withId:(id)arg1
                         withId:(id)arg2;

- (void)traceWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                   withNSString:(NSString *)msg
                withNSException:(NSException *)t;

- (void)traceWithNSString:(NSString *)msg;

- (void)traceWithNSString:(NSString *)format
                   withId:(id)arg;

- (void)traceWithNSString:(NSString *)format
        withNSObjectArray:(IOSObjectArray *)arguments;

- (void)traceWithNSString:(NSString *)format
                   withId:(id)arg1
                   withId:(id)arg2;

- (void)traceWithNSString:(NSString *)msg
          withNSException:(NSException *)t;

- (void)warnWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                  withNSString:(NSString *)msg;

- (void)warnWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                  withNSString:(NSString *)format
                        withId:(id)arg;

- (void)warnWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                  withNSString:(NSString *)format
             withNSObjectArray:(IOSObjectArray *)arguments;

- (void)warnWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                  withNSString:(NSString *)format
                        withId:(id)arg1
                        withId:(id)arg2;

- (void)warnWithOrgSlf4jMarker:(id<OrgSlf4jMarker>)marker
                  withNSString:(NSString *)msg
               withNSException:(NSException *)t;

- (void)warnWithNSString:(NSString *)msg;

- (void)warnWithNSString:(NSString *)format
                  withId:(id)arg;

- (void)warnWithNSString:(NSString *)format
       withNSObjectArray:(IOSObjectArray *)arguments;

- (void)warnWithNSString:(NSString *)format
                  withId:(id)arg1
                  withId:(id)arg2;

- (void)warnWithNSString:(NSString *)msg
         withNSException:(NSException *)t;

#pragma mark Package-Private

- (id<OrgSlf4jLogger>)delegate;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgSlf4jHelpersSubstituteLogger)

FOUNDATION_EXPORT void OrgSlf4jHelpersSubstituteLogger_initWithNSString_(OrgSlf4jHelpersSubstituteLogger *self, NSString *name);

FOUNDATION_EXPORT OrgSlf4jHelpersSubstituteLogger *new_OrgSlf4jHelpersSubstituteLogger_initWithNSString_(NSString *name) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgSlf4jHelpersSubstituteLogger *create_OrgSlf4jHelpersSubstituteLogger_initWithNSString_(NSString *name);

J2OBJC_TYPE_LITERAL_HEADER(OrgSlf4jHelpersSubstituteLogger)

#endif

#pragma pop_macro("INCLUDE_ALL_SubstituteLogger")
