//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/javax/sip/header/AcceptHeader.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidJavaxSipHeaderAcceptHeader")
#ifdef RESTRICT_AndroidJavaxSipHeaderAcceptHeader
#define INCLUDE_ALL_AndroidJavaxSipHeaderAcceptHeader 0
#else
#define INCLUDE_ALL_AndroidJavaxSipHeaderAcceptHeader 1
#endif
#undef RESTRICT_AndroidJavaxSipHeaderAcceptHeader

#if !defined (AndroidJavaxSipHeaderAcceptHeader_) && (INCLUDE_ALL_AndroidJavaxSipHeaderAcceptHeader || defined(INCLUDE_AndroidJavaxSipHeaderAcceptHeader))
#define AndroidJavaxSipHeaderAcceptHeader_

#define RESTRICT_AndroidJavaxSipHeaderMediaType 1
#define INCLUDE_AndroidJavaxSipHeaderMediaType 1
#include "android/javax/sip/header/MediaType.h"

#define RESTRICT_AndroidJavaxSipHeaderParameters 1
#define INCLUDE_AndroidJavaxSipHeaderParameters 1
#include "android/javax/sip/header/Parameters.h"

#define RESTRICT_AndroidJavaxSipHeaderHeader 1
#define INCLUDE_AndroidJavaxSipHeaderHeader 1
#include "android/javax/sip/header/Header.h"

@protocol AndroidJavaxSipHeaderAcceptHeader < AndroidJavaxSipHeaderMediaType, AndroidJavaxSipHeaderParameters, AndroidJavaxSipHeaderHeader, JavaObject >

- (void)setQValueWithFloat:(jfloat)qValue;

- (jfloat)getQValue;

- (jboolean)allowsAllContentSubTypes;

- (jboolean)allowsAllContentTypes;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidJavaxSipHeaderAcceptHeader)

inline NSString *AndroidJavaxSipHeaderAcceptHeader_get_NAME();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidJavaxSipHeaderAcceptHeader_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidJavaxSipHeaderAcceptHeader, NAME, NSString *)

J2OBJC_TYPE_LITERAL_HEADER(AndroidJavaxSipHeaderAcceptHeader)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidJavaxSipHeaderAcceptHeader")
