//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/javax/sip/header/CallIdHeader.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidJavaxSipHeaderCallIdHeader")
#ifdef RESTRICT_AndroidJavaxSipHeaderCallIdHeader
#define INCLUDE_ALL_AndroidJavaxSipHeaderCallIdHeader 0
#else
#define INCLUDE_ALL_AndroidJavaxSipHeaderCallIdHeader 1
#endif
#undef RESTRICT_AndroidJavaxSipHeaderCallIdHeader

#if !defined (AndroidJavaxSipHeaderCallIdHeader_) && (INCLUDE_ALL_AndroidJavaxSipHeaderCallIdHeader || defined(INCLUDE_AndroidJavaxSipHeaderCallIdHeader))
#define AndroidJavaxSipHeaderCallIdHeader_

#define RESTRICT_AndroidJavaxSipHeaderHeader 1
#define INCLUDE_AndroidJavaxSipHeaderHeader 1
#include "android/javax/sip/header/Header.h"

@protocol AndroidJavaxSipHeaderCallIdHeader < AndroidJavaxSipHeaderHeader, JavaObject >

- (void)setCallIdWithNSString:(NSString *)callId;

- (NSString *)getCallId;

- (jboolean)isEqual:(id)obj;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidJavaxSipHeaderCallIdHeader)

inline NSString *AndroidJavaxSipHeaderCallIdHeader_get_NAME();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidJavaxSipHeaderCallIdHeader_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidJavaxSipHeaderCallIdHeader, NAME, NSString *)

J2OBJC_TYPE_LITERAL_HEADER(AndroidJavaxSipHeaderCallIdHeader)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidJavaxSipHeaderCallIdHeader")
