//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/javax/sip/header/ErrorInfoHeader.java
//

#include "J2ObjC_source.h"
#include "android/javax/sip/header/ErrorInfoHeader.h"

@interface AndroidJavaxSipHeaderErrorInfoHeader : NSObject

@end

NSString *AndroidJavaxSipHeaderErrorInfoHeader_NAME = @"Error-Info";

@implementation AndroidJavaxSipHeaderErrorInfoHeader

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "LAndroidJavaxSipAddressURI;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 2, 3, 4, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(setErrorInfoWithAndroidJavaxSipAddressURI:);
  methods[1].selector = @selector(getErrorInfo);
  methods[2].selector = @selector(setErrorMessageWithNSString:);
  methods[3].selector = @selector(getErrorMessage);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 5, -1, -1 },
  };
  static const void *ptrTable[] = { "setErrorInfo", "LAndroidJavaxSipAddressURI;", "setErrorMessage", "LNSString;", "LJavaTextParseException;", &AndroidJavaxSipHeaderErrorInfoHeader_NAME };
  static const J2ObjcClassInfo _AndroidJavaxSipHeaderErrorInfoHeader = { "ErrorInfoHeader", "android.javax.sip.header", ptrTable, methods, fields, 7, 0x609, 4, 1, -1, -1, -1, -1, -1 };
  return &_AndroidJavaxSipHeaderErrorInfoHeader;
}

- (id)copyWithZone:(NSZone *)zone {
  return [[self java_clone] retain];
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(AndroidJavaxSipHeaderErrorInfoHeader)
