//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/javax/sip/header/MaxForwardsHeader.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidJavaxSipHeaderMaxForwardsHeader")
#ifdef RESTRICT_AndroidJavaxSipHeaderMaxForwardsHeader
#define INCLUDE_ALL_AndroidJavaxSipHeaderMaxForwardsHeader 0
#else
#define INCLUDE_ALL_AndroidJavaxSipHeaderMaxForwardsHeader 1
#endif
#undef RESTRICT_AndroidJavaxSipHeaderMaxForwardsHeader

#if !defined (AndroidJavaxSipHeaderMaxForwardsHeader_) && (INCLUDE_ALL_AndroidJavaxSipHeaderMaxForwardsHeader || defined(INCLUDE_AndroidJavaxSipHeaderMaxForwardsHeader))
#define AndroidJavaxSipHeaderMaxForwardsHeader_

#define RESTRICT_AndroidJavaxSipHeaderHeader 1
#define INCLUDE_AndroidJavaxSipHeaderHeader 1
#include "android/javax/sip/header/Header.h"

@protocol AndroidJavaxSipHeaderMaxForwardsHeader < AndroidJavaxSipHeaderHeader, JavaObject >

- (void)decrementMaxForwards;

- (jint)getMaxForwards;

- (void)setMaxForwardsWithInt:(jint)maxForwards;

- (jboolean)isEqual:(id)obj;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidJavaxSipHeaderMaxForwardsHeader)

inline NSString *AndroidJavaxSipHeaderMaxForwardsHeader_get_NAME();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *AndroidJavaxSipHeaderMaxForwardsHeader_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidJavaxSipHeaderMaxForwardsHeader, NAME, NSString *)

J2OBJC_TYPE_LITERAL_HEADER(AndroidJavaxSipHeaderMaxForwardsHeader)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidJavaxSipHeaderMaxForwardsHeader")
