//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/javax/sip/header/MediaType.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidJavaxSipHeaderMediaType")
#ifdef RESTRICT_AndroidJavaxSipHeaderMediaType
#define INCLUDE_ALL_AndroidJavaxSipHeaderMediaType 0
#else
#define INCLUDE_ALL_AndroidJavaxSipHeaderMediaType 1
#endif
#undef RESTRICT_AndroidJavaxSipHeaderMediaType

#if !defined (AndroidJavaxSipHeaderMediaType_) && (INCLUDE_ALL_AndroidJavaxSipHeaderMediaType || defined(INCLUDE_AndroidJavaxSipHeaderMediaType))
#define AndroidJavaxSipHeaderMediaType_

@protocol AndroidJavaxSipHeaderMediaType < JavaObject >

- (void)setContentTypeWithNSString:(NSString *)contentType;

- (NSString *)getContentType;

- (void)setContentSubTypeWithNSString:(NSString *)contentSubType;

- (NSString *)getContentSubType;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidJavaxSipHeaderMediaType)

J2OBJC_TYPE_LITERAL_HEADER(AndroidJavaxSipHeaderMediaType)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidJavaxSipHeaderMediaType")
