//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/javax/sip/header/ReasonHeader.java
//

#include "J2ObjC_source.h"
#include "android/javax/sip/header/ReasonHeader.h"

@interface AndroidJavaxSipHeaderReasonHeader : NSObject

@end

NSString *AndroidJavaxSipHeaderReasonHeader_NAME = @"Reason";

@implementation AndroidJavaxSipHeaderReasonHeader

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "I", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 0, 1, 2, -1, -1, -1 },
    { NULL, "V", 0x401, 3, 4, 5, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 6, 4, 5, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getCause);
  methods[1].selector = @selector(setCauseWithInt:);
  methods[2].selector = @selector(setProtocolWithNSString:);
  methods[3].selector = @selector(getProtocol);
  methods[4].selector = @selector(setTextWithNSString:);
  methods[5].selector = @selector(getText);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 7, -1, -1 },
  };
  static const void *ptrTable[] = { "setCause", "I", "LAndroidJavaxSipInvalidArgumentException;", "setProtocol", "LNSString;", "LJavaTextParseException;", "setText", &AndroidJavaxSipHeaderReasonHeader_NAME };
  static const J2ObjcClassInfo _AndroidJavaxSipHeaderReasonHeader = { "ReasonHeader", "android.javax.sip.header", ptrTable, methods, fields, 7, 0x609, 6, 1, -1, -1, -1, -1, -1 };
  return &_AndroidJavaxSipHeaderReasonHeader;
}

- (id)copyWithZone:(NSZone *)zone {
  return [[self java_clone] retain];
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(AndroidJavaxSipHeaderReasonHeader)
