//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/javax/sip/address/Address.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidJavaxSipAddressAddress")
#ifdef RESTRICT_AndroidJavaxSipAddressAddress
#define INCLUDE_ALL_AndroidJavaxSipAddressAddress 0
#else
#define INCLUDE_ALL_AndroidJavaxSipAddressAddress 1
#endif
#undef RESTRICT_AndroidJavaxSipAddressAddress

#if !defined (AndroidJavaxSipAddressAddress_) && (INCLUDE_ALL_AndroidJavaxSipAddressAddress || defined(INCLUDE_AndroidJavaxSipAddressAddress))
#define AndroidJavaxSipAddressAddress_

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@protocol AndroidJavaxSipAddressURI;

@protocol AndroidJavaxSipAddressAddress < NSCopying, JavaIoSerializable, JavaObject >

- (void)setDisplayNameWithNSString:(NSString *)displayName;

- (NSString *)getDisplayName;

- (void)setURIWithAndroidJavaxSipAddressURI:(id<AndroidJavaxSipAddressURI>)uri;

- (id<AndroidJavaxSipAddressURI>)getURI;

- (NSString *)description;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

- (jboolean)isWildcard;

- (id)java_clone;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidJavaxSipAddressAddress)

J2OBJC_TYPE_LITERAL_HEADER(AndroidJavaxSipAddressAddress)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidJavaxSipAddressAddress")
