//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/javax/sip/address/URI.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidJavaxSipAddressURI")
#ifdef RESTRICT_AndroidJavaxSipAddressURI
#define INCLUDE_ALL_AndroidJavaxSipAddressURI 0
#else
#define INCLUDE_ALL_AndroidJavaxSipAddressURI 1
#endif
#undef RESTRICT_AndroidJavaxSipAddressURI

#if !defined (AndroidJavaxSipAddressURI_) && (INCLUDE_ALL_AndroidJavaxSipAddressURI || defined(INCLUDE_AndroidJavaxSipAddressURI))
#define AndroidJavaxSipAddressURI_

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@protocol AndroidJavaxSipAddressURI < NSCopying, JavaIoSerializable, JavaObject >

- (NSString *)getScheme;

- (id)java_clone;

- (jboolean)isSipURI;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidJavaxSipAddressURI)

J2OBJC_TYPE_LITERAL_HEADER(AndroidJavaxSipAddressURI)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidJavaxSipAddressURI")
