//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/address/TelURLImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSipAddressTelURLImpl")
#ifdef RESTRICT_AndroidGovNistJavaxSipAddressTelURLImpl
#define INCLUDE_ALL_AndroidGovNistJavaxSipAddressTelURLImpl 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSipAddressTelURLImpl 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSipAddressTelURLImpl

#if !defined (AndroidGovNistJavaxSipAddressTelURLImpl_) && (INCLUDE_ALL_AndroidGovNistJavaxSipAddressTelURLImpl || defined(INCLUDE_AndroidGovNistJavaxSipAddressTelURLImpl))
#define AndroidGovNistJavaxSipAddressTelURLImpl_

#define RESTRICT_AndroidGovNistJavaxSipAddressGenericURI 1
#define INCLUDE_AndroidGovNistJavaxSipAddressGenericURI 1
#include "android/gov/nist/javax/sip/address/GenericURI.h"

#define RESTRICT_AndroidJavaxSipAddressTelURL 1
#define INCLUDE_AndroidJavaxSipAddressTelURL 1
#include "android/javax/sip/address/TelURL.h"

@class AndroidGovNistCoreNameValueList;
@class AndroidGovNistJavaxSipAddressTelephoneNumber;
@class JavaLangStringBuilder;
@protocol JavaUtilIterator;

@interface AndroidGovNistJavaxSipAddressTelURLImpl : AndroidGovNistJavaxSipAddressGenericURI < AndroidJavaxSipAddressTelURL > {
 @public
  AndroidGovNistJavaxSipAddressTelephoneNumber *telephoneNumber_;
}

#pragma mark Public

- (instancetype)init;

- (id)java_clone;

- (NSString *)encode;

- (JavaLangStringBuilder *)encodeWithJavaLangStringBuilder:(JavaLangStringBuilder *)buffer;

- (NSString *)getIsdnSubAddress;

- (NSString *)getParameterWithNSString:(NSString *)parameterName;

- (id<JavaUtilIterator>)getParameterNames;

- (AndroidGovNistCoreNameValueList *)getParameters;

- (NSString *)getPhoneContext;

- (NSString *)getPhoneNumber;

- (NSString *)getPostDial;

- (NSString *)getScheme;

- (jboolean)isGlobal;

- (jboolean)isSipURI;

- (void)removeParameterWithNSString:(NSString *)name;

- (void)setGlobalWithBoolean:(jboolean)global;

- (void)setIsdnSubAddressWithNSString:(NSString *)isdnSubAddress;

- (void)setParameterWithNSString:(NSString *)name
                    withNSString:(NSString *)value;

- (void)setPhoneContextWithNSString:(NSString *)phoneContext;

- (void)setPhoneNumberWithNSString:(NSString *)telephoneNumber;

- (void)setPostDialWithNSString:(NSString *)postDial;

- (void)setTelephoneNumberWithAndroidGovNistJavaxSipAddressTelephoneNumber:(AndroidGovNistJavaxSipAddressTelephoneNumber *)telephoneNumber;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSipAddressTelURLImpl)

J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSipAddressTelURLImpl, telephoneNumber_, AndroidGovNistJavaxSipAddressTelephoneNumber *)

FOUNDATION_EXPORT void AndroidGovNistJavaxSipAddressTelURLImpl_init(AndroidGovNistJavaxSipAddressTelURLImpl *self);

FOUNDATION_EXPORT AndroidGovNistJavaxSipAddressTelURLImpl *new_AndroidGovNistJavaxSipAddressTelURLImpl_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSipAddressTelURLImpl *create_AndroidGovNistJavaxSipAddressTelURLImpl_init();

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSipAddressTelURLImpl)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSipAddressTelURLImpl")
