//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/message/ResponseExt.java
//

#include "J2ObjC_source.h"
#include "android/gov/nist/javax/sip/message/ResponseExt.h"

@interface AndroidGovNistJavaxSipMessageResponseExt : NSObject

@end

@implementation AndroidGovNistJavaxSipMessageResponseExt

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _AndroidGovNistJavaxSipMessageResponseExt = { "ResponseExt", "android.gov.nist.javax.sip.message", NULL, NULL, NULL, 7, 0x609, 0, 0, -1, -1, -1, -1, -1 };
  return &_AndroidGovNistJavaxSipMessageResponseExt;
}

- (id)copyWithZone:(NSZone *)zone {
  return [[self java_clone] retain];
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(AndroidGovNistJavaxSipMessageResponseExt)
