//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/parser/extensions/ReferencesParser.java
//

#include "J2ObjC_source.h"
#include "android/gov/nist/core/LexerCore.h"
#include "android/gov/nist/core/ParserCore.h"
#include "android/gov/nist/javax/sip/header/SIPHeader.h"
#include "android/gov/nist/javax/sip/header/extensions/References.h"
#include "android/gov/nist/javax/sip/parser/Lexer.h"
#include "android/gov/nist/javax/sip/parser/ParametersParser.h"
#include "android/gov/nist/javax/sip/parser/TokenTypes.h"
#include "android/gov/nist/javax/sip/parser/extensions/ReferencesParser.h"

@implementation AndroidGovNistJavaxSipParserExtensionsReferencesParser

- (instancetype)initWithNSString:(NSString *)references {
  AndroidGovNistJavaxSipParserExtensionsReferencesParser_initWithNSString_(self, references);
  return self;
}

- (instancetype)initWithAndroidGovNistJavaxSipParserLexer:(AndroidGovNistJavaxSipParserLexer *)lexer {
  AndroidGovNistJavaxSipParserExtensionsReferencesParser_initWithAndroidGovNistJavaxSipParserLexer_(self, lexer);
  return self;
}

- (AndroidGovNistJavaxSipHeaderSIPHeader *)parse {
  if (JreLoadStatic(AndroidGovNistCoreParserCore, debug)) [self dbg_enterWithNSString:@"ReasonParser.parse"];
  @try {
    [self headerNameWithInt:AndroidGovNistJavaxSipParserTokenTypes_REFERENCES];
    AndroidGovNistJavaxSipHeaderExtensionsReferences *references = create_AndroidGovNistJavaxSipHeaderExtensionsReferences_init();
    [((AndroidGovNistCoreLexerCore *) nil_chk(self->lexer_)) SPorHT];
    NSString *callId = [((AndroidGovNistCoreLexerCore *) nil_chk(lexer_)) byteStringNoSemicolon];
    [references setCallIdWithNSString:callId];
    [super parseWithAndroidGovNistJavaxSipHeaderParametersHeader:references];
    return references;
  }
  @finally {
    if (JreLoadStatic(AndroidGovNistCoreParserCore, debug)) [self dbg_leaveWithNSString:@"ReferencesParser.parse"];
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x4, -1, 1, -1, -1, -1, -1 },
    { NULL, "LAndroidGovNistJavaxSipHeaderSIPHeader;", 0x1, -1, -1, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithNSString:);
  methods[1].selector = @selector(initWithAndroidGovNistJavaxSipParserLexer:);
  methods[2].selector = @selector(parse);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LNSString;", "LAndroidGovNistJavaxSipParserLexer;", "LJavaTextParseException;" };
  static const J2ObjcClassInfo _AndroidGovNistJavaxSipParserExtensionsReferencesParser = { "ReferencesParser", "android.gov.nist.javax.sip.parser.extensions", ptrTable, methods, NULL, 7, 0x1, 3, 0, -1, -1, -1, -1, -1 };
  return &_AndroidGovNistJavaxSipParserExtensionsReferencesParser;
}

@end

void AndroidGovNistJavaxSipParserExtensionsReferencesParser_initWithNSString_(AndroidGovNistJavaxSipParserExtensionsReferencesParser *self, NSString *references) {
  AndroidGovNistJavaxSipParserParametersParser_initWithNSString_(self, references);
}

AndroidGovNistJavaxSipParserExtensionsReferencesParser *new_AndroidGovNistJavaxSipParserExtensionsReferencesParser_initWithNSString_(NSString *references) {
  J2OBJC_NEW_IMPL(AndroidGovNistJavaxSipParserExtensionsReferencesParser, initWithNSString_, references)
}

AndroidGovNistJavaxSipParserExtensionsReferencesParser *create_AndroidGovNistJavaxSipParserExtensionsReferencesParser_initWithNSString_(NSString *references) {
  J2OBJC_CREATE_IMPL(AndroidGovNistJavaxSipParserExtensionsReferencesParser, initWithNSString_, references)
}

void AndroidGovNistJavaxSipParserExtensionsReferencesParser_initWithAndroidGovNistJavaxSipParserLexer_(AndroidGovNistJavaxSipParserExtensionsReferencesParser *self, AndroidGovNistJavaxSipParserLexer *lexer) {
  AndroidGovNistJavaxSipParserParametersParser_initWithAndroidGovNistJavaxSipParserLexer_(self, lexer);
}

AndroidGovNistJavaxSipParserExtensionsReferencesParser *new_AndroidGovNistJavaxSipParserExtensionsReferencesParser_initWithAndroidGovNistJavaxSipParserLexer_(AndroidGovNistJavaxSipParserLexer *lexer) {
  J2OBJC_NEW_IMPL(AndroidGovNistJavaxSipParserExtensionsReferencesParser, initWithAndroidGovNistJavaxSipParserLexer_, lexer)
}

AndroidGovNistJavaxSipParserExtensionsReferencesParser *create_AndroidGovNistJavaxSipParserExtensionsReferencesParser_initWithAndroidGovNistJavaxSipParserLexer_(AndroidGovNistJavaxSipParserLexer *lexer) {
  J2OBJC_CREATE_IMPL(AndroidGovNistJavaxSipParserExtensionsReferencesParser, initWithAndroidGovNistJavaxSipParserLexer_, lexer)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AndroidGovNistJavaxSipParserExtensionsReferencesParser)
