//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/parser/extensions/ReplacesParser.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "android/gov/nist/core/LexerCore.h"
#include "android/gov/nist/core/ParserCore.h"
#include "android/gov/nist/javax/sip/header/SIPHeader.h"
#include "android/gov/nist/javax/sip/header/extensions/Replaces.h"
#include "android/gov/nist/javax/sip/parser/Lexer.h"
#include "android/gov/nist/javax/sip/parser/ParametersParser.h"
#include "android/gov/nist/javax/sip/parser/TokenTypes.h"
#include "android/gov/nist/javax/sip/parser/extensions/ReplacesParser.h"
#include "java/io/PrintStream.h"
#include "java/lang/System.h"

@implementation AndroidGovNistJavaxSipParserExtensionsReplacesParser

- (instancetype)initWithNSString:(NSString *)callID {
  AndroidGovNistJavaxSipParserExtensionsReplacesParser_initWithNSString_(self, callID);
  return self;
}

- (instancetype)initWithAndroidGovNistJavaxSipParserLexer:(AndroidGovNistJavaxSipParserLexer *)lexer {
  AndroidGovNistJavaxSipParserExtensionsReplacesParser_initWithAndroidGovNistJavaxSipParserLexer_(self, lexer);
  return self;
}

- (AndroidGovNistJavaxSipHeaderSIPHeader *)parse {
  if (JreLoadStatic(AndroidGovNistCoreParserCore, debug)) [self dbg_enterWithNSString:@"parse"];
  @try {
    [self headerNameWithInt:AndroidGovNistJavaxSipParserTokenTypes_REPLACES_TO];
    AndroidGovNistJavaxSipHeaderExtensionsReplaces *replaces = create_AndroidGovNistJavaxSipHeaderExtensionsReplaces_init();
    [((AndroidGovNistCoreLexerCore *) nil_chk(self->lexer_)) SPorHT];
    NSString *callId = [((AndroidGovNistCoreLexerCore *) nil_chk(lexer_)) byteStringNoSemicolon];
    [((AndroidGovNistCoreLexerCore *) nil_chk(self->lexer_)) SPorHT];
    [super parseWithAndroidGovNistJavaxSipHeaderParametersHeader:replaces];
    [replaces setCallIdWithNSString:callId];
    return replaces;
  }
  @finally {
    if (JreLoadStatic(AndroidGovNistCoreParserCore, debug)) [self dbg_leaveWithNSString:@"parse"];
  }
}

+ (void)mainWithNSStringArray:(IOSObjectArray *)args {
  AndroidGovNistJavaxSipParserExtensionsReplacesParser_mainWithNSStringArray_(args);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x4, -1, 1, -1, -1, -1, -1 },
    { NULL, "LAndroidGovNistJavaxSipHeaderSIPHeader;", 0x1, -1, -1, 2, -1, -1, -1 },
    { NULL, "V", 0x9, 3, 4, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithNSString:);
  methods[1].selector = @selector(initWithAndroidGovNistJavaxSipParserLexer:);
  methods[2].selector = @selector(parse);
  methods[3].selector = @selector(mainWithNSStringArray:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LNSString;", "LAndroidGovNistJavaxSipParserLexer;", "LJavaTextParseException;", "main", "[LNSString;" };
  static const J2ObjcClassInfo _AndroidGovNistJavaxSipParserExtensionsReplacesParser = { "ReplacesParser", "android.gov.nist.javax.sip.parser.extensions", ptrTable, methods, NULL, 7, 0x1, 4, 0, -1, -1, -1, -1, -1 };
  return &_AndroidGovNistJavaxSipParserExtensionsReplacesParser;
}

@end

void AndroidGovNistJavaxSipParserExtensionsReplacesParser_initWithNSString_(AndroidGovNistJavaxSipParserExtensionsReplacesParser *self, NSString *callID) {
  AndroidGovNistJavaxSipParserParametersParser_initWithNSString_(self, callID);
}

AndroidGovNistJavaxSipParserExtensionsReplacesParser *new_AndroidGovNistJavaxSipParserExtensionsReplacesParser_initWithNSString_(NSString *callID) {
  J2OBJC_NEW_IMPL(AndroidGovNistJavaxSipParserExtensionsReplacesParser, initWithNSString_, callID)
}

AndroidGovNistJavaxSipParserExtensionsReplacesParser *create_AndroidGovNistJavaxSipParserExtensionsReplacesParser_initWithNSString_(NSString *callID) {
  J2OBJC_CREATE_IMPL(AndroidGovNistJavaxSipParserExtensionsReplacesParser, initWithNSString_, callID)
}

void AndroidGovNistJavaxSipParserExtensionsReplacesParser_initWithAndroidGovNistJavaxSipParserLexer_(AndroidGovNistJavaxSipParserExtensionsReplacesParser *self, AndroidGovNistJavaxSipParserLexer *lexer) {
  AndroidGovNistJavaxSipParserParametersParser_initWithAndroidGovNistJavaxSipParserLexer_(self, lexer);
}

AndroidGovNistJavaxSipParserExtensionsReplacesParser *new_AndroidGovNistJavaxSipParserExtensionsReplacesParser_initWithAndroidGovNistJavaxSipParserLexer_(AndroidGovNistJavaxSipParserLexer *lexer) {
  J2OBJC_NEW_IMPL(AndroidGovNistJavaxSipParserExtensionsReplacesParser, initWithAndroidGovNistJavaxSipParserLexer_, lexer)
}

AndroidGovNistJavaxSipParserExtensionsReplacesParser *create_AndroidGovNistJavaxSipParserExtensionsReplacesParser_initWithAndroidGovNistJavaxSipParserLexer_(AndroidGovNistJavaxSipParserLexer *lexer) {
  J2OBJC_CREATE_IMPL(AndroidGovNistJavaxSipParserExtensionsReplacesParser, initWithAndroidGovNistJavaxSipParserLexer_, lexer)
}

void AndroidGovNistJavaxSipParserExtensionsReplacesParser_mainWithNSStringArray_(IOSObjectArray *args) {
  AndroidGovNistJavaxSipParserExtensionsReplacesParser_initialize();
  IOSObjectArray *to = [IOSObjectArray arrayWithObjects:(id[]){ @"Replaces: 12345th5z8z\n", @"Replaces: 12345th5z8z;to-tag=tozght6-45;from-tag=fromzght789-337-2\n" } count:2 type:NSString_class_()];
  for (jint i = 0; i < to->size_; i++) {
    AndroidGovNistJavaxSipParserExtensionsReplacesParser *tp = create_AndroidGovNistJavaxSipParserExtensionsReplacesParser_initWithNSString_(IOSObjectArray_Get(to, i));
    AndroidGovNistJavaxSipHeaderExtensionsReplaces *t = (AndroidGovNistJavaxSipHeaderExtensionsReplaces *) cast_chk([tp parse], [AndroidGovNistJavaxSipHeaderExtensionsReplaces class]);
    [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, out))) printlnWithNSString:JreStrcat("$$", @"Parsing => ", IOSObjectArray_Get(to, i))];
    [JreLoadStatic(JavaLangSystem, out) printWithNSString:JreStrcat("$$$", @"encoded = ", [((AndroidGovNistJavaxSipHeaderExtensionsReplaces *) nil_chk(t)) encode], @"==> ")];
    [JreLoadStatic(JavaLangSystem, out) printlnWithNSString:JreStrcat("$$$$$$", @"callId ", [t getCallId], @" from-tag=", [t getFromTag], @" to-tag=", [t getToTag])];
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AndroidGovNistJavaxSipParserExtensionsReplacesParser)
