//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/javax/sip/DialogTerminatedEvent.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidJavaxSipDialogTerminatedEvent")
#ifdef RESTRICT_AndroidJavaxSipDialogTerminatedEvent
#define INCLUDE_ALL_AndroidJavaxSipDialogTerminatedEvent 0
#else
#define INCLUDE_ALL_AndroidJavaxSipDialogTerminatedEvent 1
#endif
#undef RESTRICT_AndroidJavaxSipDialogTerminatedEvent

#if !defined (AndroidJavaxSipDialogTerminatedEvent_) && (INCLUDE_ALL_AndroidJavaxSipDialogTerminatedEvent || defined(INCLUDE_AndroidJavaxSipDialogTerminatedEvent))
#define AndroidJavaxSipDialogTerminatedEvent_

#define RESTRICT_JavaUtilEventObject 1
#define INCLUDE_JavaUtilEventObject 1
#include "java/util/EventObject.h"

@protocol AndroidJavaxSipDialog;

@interface AndroidJavaxSipDialogTerminatedEvent : JavaUtilEventObject

#pragma mark Public

- (instancetype)initWithId:(id)source
 withAndroidJavaxSipDialog:(id<AndroidJavaxSipDialog>)dialog;

- (id<AndroidJavaxSipDialog>)getDialog;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidJavaxSipDialogTerminatedEvent)

FOUNDATION_EXPORT void AndroidJavaxSipDialogTerminatedEvent_initWithId_withAndroidJavaxSipDialog_(AndroidJavaxSipDialogTerminatedEvent *self, id source, id<AndroidJavaxSipDialog> dialog);

FOUNDATION_EXPORT AndroidJavaxSipDialogTerminatedEvent *new_AndroidJavaxSipDialogTerminatedEvent_initWithId_withAndroidJavaxSipDialog_(id source, id<AndroidJavaxSipDialog> dialog) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidJavaxSipDialogTerminatedEvent *create_AndroidJavaxSipDialogTerminatedEvent_initWithId_withAndroidJavaxSipDialog_(id source, id<AndroidJavaxSipDialog> dialog);

J2OBJC_TYPE_LITERAL_HEADER(AndroidJavaxSipDialogTerminatedEvent)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidJavaxSipDialogTerminatedEvent")
