//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/javax/sip/ObjectInUseException.java
//

#include "J2ObjC_source.h"
#include "android/javax/sip/ObjectInUseException.h"
#include "android/javax/sip/SipException.h"

@implementation AndroidJavaxSipObjectInUseException

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  AndroidJavaxSipObjectInUseException_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)message {
  AndroidJavaxSipObjectInUseException_initWithNSString_(self, message);
  return self;
}

- (instancetype)initWithNSString:(NSString *)message
                 withNSException:(NSException *)cause {
  AndroidJavaxSipObjectInUseException_initWithNSString_withNSException_(self, message, cause);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithNSString:);
  methods[2].selector = @selector(initWithNSString:withNSException:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LNSString;", "LNSString;LNSException;" };
  static const J2ObjcClassInfo _AndroidJavaxSipObjectInUseException = { "ObjectInUseException", "android.javax.sip", ptrTable, methods, NULL, 7, 0x1, 3, 0, -1, -1, -1, -1, -1 };
  return &_AndroidJavaxSipObjectInUseException;
}

@end

void AndroidJavaxSipObjectInUseException_init(AndroidJavaxSipObjectInUseException *self) {
  AndroidJavaxSipSipException_init(self);
}

AndroidJavaxSipObjectInUseException *new_AndroidJavaxSipObjectInUseException_init() {
  J2OBJC_NEW_IMPL(AndroidJavaxSipObjectInUseException, init)
}

AndroidJavaxSipObjectInUseException *create_AndroidJavaxSipObjectInUseException_init() {
  J2OBJC_CREATE_IMPL(AndroidJavaxSipObjectInUseException, init)
}

void AndroidJavaxSipObjectInUseException_initWithNSString_(AndroidJavaxSipObjectInUseException *self, NSString *message) {
  AndroidJavaxSipSipException_initWithNSString_(self, message);
}

AndroidJavaxSipObjectInUseException *new_AndroidJavaxSipObjectInUseException_initWithNSString_(NSString *message) {
  J2OBJC_NEW_IMPL(AndroidJavaxSipObjectInUseException, initWithNSString_, message)
}

AndroidJavaxSipObjectInUseException *create_AndroidJavaxSipObjectInUseException_initWithNSString_(NSString *message) {
  J2OBJC_CREATE_IMPL(AndroidJavaxSipObjectInUseException, initWithNSString_, message)
}

void AndroidJavaxSipObjectInUseException_initWithNSString_withNSException_(AndroidJavaxSipObjectInUseException *self, NSString *message, NSException *cause) {
  AndroidJavaxSipSipException_initWithNSString_withNSException_(self, message, cause);
}

AndroidJavaxSipObjectInUseException *new_AndroidJavaxSipObjectInUseException_initWithNSString_withNSException_(NSString *message, NSException *cause) {
  J2OBJC_NEW_IMPL(AndroidJavaxSipObjectInUseException, initWithNSString_withNSException_, message, cause)
}

AndroidJavaxSipObjectInUseException *create_AndroidJavaxSipObjectInUseException_initWithNSString_withNSException_(NSString *message, NSException *cause) {
  J2OBJC_CREATE_IMPL(AndroidJavaxSipObjectInUseException, initWithNSString_withNSException_, message, cause)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AndroidJavaxSipObjectInUseException)
