//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/javax/sip/TransactionAlreadyExistsException.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidJavaxSipTransactionAlreadyExistsException")
#ifdef RESTRICT_AndroidJavaxSipTransactionAlreadyExistsException
#define INCLUDE_ALL_AndroidJavaxSipTransactionAlreadyExistsException 0
#else
#define INCLUDE_ALL_AndroidJavaxSipTransactionAlreadyExistsException 1
#endif
#undef RESTRICT_AndroidJavaxSipTransactionAlreadyExistsException

#if !defined (AndroidJavaxSipTransactionAlreadyExistsException_) && (INCLUDE_ALL_AndroidJavaxSipTransactionAlreadyExistsException || defined(INCLUDE_AndroidJavaxSipTransactionAlreadyExistsException))
#define AndroidJavaxSipTransactionAlreadyExistsException_

#define RESTRICT_AndroidJavaxSipSipException 1
#define INCLUDE_AndroidJavaxSipSipException 1
#include "android/javax/sip/SipException.h"

@interface AndroidJavaxSipTransactionAlreadyExistsException : AndroidJavaxSipSipException

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)message;

- (instancetype)initWithNSString:(NSString *)message
                 withNSException:(NSException *)cause;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidJavaxSipTransactionAlreadyExistsException)

FOUNDATION_EXPORT void AndroidJavaxSipTransactionAlreadyExistsException_init(AndroidJavaxSipTransactionAlreadyExistsException *self);

FOUNDATION_EXPORT AndroidJavaxSipTransactionAlreadyExistsException *new_AndroidJavaxSipTransactionAlreadyExistsException_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidJavaxSipTransactionAlreadyExistsException *create_AndroidJavaxSipTransactionAlreadyExistsException_init();

FOUNDATION_EXPORT void AndroidJavaxSipTransactionAlreadyExistsException_initWithNSString_(AndroidJavaxSipTransactionAlreadyExistsException *self, NSString *message);

FOUNDATION_EXPORT AndroidJavaxSipTransactionAlreadyExistsException *new_AndroidJavaxSipTransactionAlreadyExistsException_initWithNSString_(NSString *message) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidJavaxSipTransactionAlreadyExistsException *create_AndroidJavaxSipTransactionAlreadyExistsException_initWithNSString_(NSString *message);

FOUNDATION_EXPORT void AndroidJavaxSipTransactionAlreadyExistsException_initWithNSString_withNSException_(AndroidJavaxSipTransactionAlreadyExistsException *self, NSString *message, NSException *cause);

FOUNDATION_EXPORT AndroidJavaxSipTransactionAlreadyExistsException *new_AndroidJavaxSipTransactionAlreadyExistsException_initWithNSString_withNSException_(NSString *message, NSException *cause) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidJavaxSipTransactionAlreadyExistsException *create_AndroidJavaxSipTransactionAlreadyExistsException_initWithNSString_withNSException_(NSString *message, NSException *cause);

J2OBJC_TYPE_LITERAL_HEADER(AndroidJavaxSipTransactionAlreadyExistsException)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidJavaxSipTransactionAlreadyExistsException")
