//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/javax/sip/TransactionUnavailableException.java
//

#include "J2ObjC_source.h"
#include "android/javax/sip/SipException.h"
#include "android/javax/sip/TransactionUnavailableException.h"

@implementation AndroidJavaxSipTransactionUnavailableException

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  AndroidJavaxSipTransactionUnavailableException_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)message {
  AndroidJavaxSipTransactionUnavailableException_initWithNSString_(self, message);
  return self;
}

- (instancetype)initWithNSString:(NSString *)message
                 withNSException:(NSException *)cause {
  AndroidJavaxSipTransactionUnavailableException_initWithNSString_withNSException_(self, message, cause);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithNSString:);
  methods[2].selector = @selector(initWithNSString:withNSException:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LNSString;", "LNSString;LNSException;" };
  static const J2ObjcClassInfo _AndroidJavaxSipTransactionUnavailableException = { "TransactionUnavailableException", "android.javax.sip", ptrTable, methods, NULL, 7, 0x1, 3, 0, -1, -1, -1, -1, -1 };
  return &_AndroidJavaxSipTransactionUnavailableException;
}

@end

void AndroidJavaxSipTransactionUnavailableException_init(AndroidJavaxSipTransactionUnavailableException *self) {
  AndroidJavaxSipSipException_init(self);
}

AndroidJavaxSipTransactionUnavailableException *new_AndroidJavaxSipTransactionUnavailableException_init() {
  J2OBJC_NEW_IMPL(AndroidJavaxSipTransactionUnavailableException, init)
}

AndroidJavaxSipTransactionUnavailableException *create_AndroidJavaxSipTransactionUnavailableException_init() {
  J2OBJC_CREATE_IMPL(AndroidJavaxSipTransactionUnavailableException, init)
}

void AndroidJavaxSipTransactionUnavailableException_initWithNSString_(AndroidJavaxSipTransactionUnavailableException *self, NSString *message) {
  AndroidJavaxSipSipException_initWithNSString_(self, message);
}

AndroidJavaxSipTransactionUnavailableException *new_AndroidJavaxSipTransactionUnavailableException_initWithNSString_(NSString *message) {
  J2OBJC_NEW_IMPL(AndroidJavaxSipTransactionUnavailableException, initWithNSString_, message)
}

AndroidJavaxSipTransactionUnavailableException *create_AndroidJavaxSipTransactionUnavailableException_initWithNSString_(NSString *message) {
  J2OBJC_CREATE_IMPL(AndroidJavaxSipTransactionUnavailableException, initWithNSString_, message)
}

void AndroidJavaxSipTransactionUnavailableException_initWithNSString_withNSException_(AndroidJavaxSipTransactionUnavailableException *self, NSString *message, NSException *cause) {
  AndroidJavaxSipSipException_initWithNSString_withNSException_(self, message, cause);
}

AndroidJavaxSipTransactionUnavailableException *new_AndroidJavaxSipTransactionUnavailableException_initWithNSString_withNSException_(NSString *message, NSException *cause) {
  J2OBJC_NEW_IMPL(AndroidJavaxSipTransactionUnavailableException, initWithNSString_withNSException_, message, cause)
}

AndroidJavaxSipTransactionUnavailableException *create_AndroidJavaxSipTransactionUnavailableException_initWithNSString_withNSException_(NSString *message, NSException *cause) {
  J2OBJC_CREATE_IMPL(AndroidJavaxSipTransactionUnavailableException, initWithNSString_withNSException_, message, cause)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AndroidJavaxSipTransactionUnavailableException)
