//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/header/ims/PPreferredService.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPPreferredService")
#ifdef RESTRICT_AndroidGovNistJavaxSipHeaderImsPPreferredService
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPPreferredService 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPPreferredService 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSipHeaderImsPPreferredService

#if !defined (AndroidGovNistJavaxSipHeaderImsPPreferredService_) && (INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPPreferredService || defined(INCLUDE_AndroidGovNistJavaxSipHeaderImsPPreferredService))
#define AndroidGovNistJavaxSipHeaderImsPPreferredService_

#define RESTRICT_AndroidGovNistJavaxSipHeaderSIPHeader 1
#define INCLUDE_AndroidGovNistJavaxSipHeaderSIPHeader 1
#include "android/gov/nist/javax/sip/header/SIPHeader.h"

#define RESTRICT_AndroidGovNistJavaxSipHeaderImsPPreferredServiceHeader 1
#define INCLUDE_AndroidGovNistJavaxSipHeaderImsPPreferredServiceHeader 1
#include "android/gov/nist/javax/sip/header/ims/PPreferredServiceHeader.h"

#define RESTRICT_AndroidGovNistJavaxSipHeaderImsSIPHeaderNamesIms 1
#define INCLUDE_AndroidGovNistJavaxSipHeaderImsSIPHeaderNamesIms 1
#include "android/gov/nist/javax/sip/header/ims/SIPHeaderNamesIms.h"

#define RESTRICT_AndroidJavaxSipHeaderExtensionHeader 1
#define INCLUDE_AndroidJavaxSipHeaderExtensionHeader 1
#include "android/javax/sip/header/ExtensionHeader.h"

@class JavaLangStringBuilder;

@interface AndroidGovNistJavaxSipHeaderImsPPreferredService : AndroidGovNistJavaxSipHeaderSIPHeader < AndroidGovNistJavaxSipHeaderImsPPreferredServiceHeader, AndroidGovNistJavaxSipHeaderImsSIPHeaderNamesIms, AndroidJavaxSipHeaderExtensionHeader >

#pragma mark Public

- (instancetype)init;

- (id)java_clone;

- (jboolean)isEqual:(id)other;

- (NSString *)getApplicationIdentifiers;

- (NSString *)getSubserviceIdentifiers;

- (void)setApplicationIdentifiersWithNSString:(NSString *)appids;

- (void)setSubserviceIdentifiersWithNSString:(NSString *)subservices;

- (void)setValueWithNSString:(NSString *)value;

#pragma mark Protected

- (instancetype)initWithNSString:(NSString *)name;

- (JavaLangStringBuilder *)encodeBodyWithJavaLangStringBuilder:(JavaLangStringBuilder *)retval;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSipHeaderImsPPreferredService)

FOUNDATION_EXPORT void AndroidGovNistJavaxSipHeaderImsPPreferredService_initWithNSString_(AndroidGovNistJavaxSipHeaderImsPPreferredService *self, NSString *name);

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderImsPPreferredService *new_AndroidGovNistJavaxSipHeaderImsPPreferredService_initWithNSString_(NSString *name) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderImsPPreferredService *create_AndroidGovNistJavaxSipHeaderImsPPreferredService_initWithNSString_(NSString *name);

FOUNDATION_EXPORT void AndroidGovNistJavaxSipHeaderImsPPreferredService_init(AndroidGovNistJavaxSipHeaderImsPPreferredService *self);

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderImsPPreferredService *new_AndroidGovNistJavaxSipHeaderImsPPreferredService_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderImsPPreferredService *create_AndroidGovNistJavaxSipHeaderImsPPreferredService_init();

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSipHeaderImsPPreferredService)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPPreferredService")
