//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/header/ims/PServedUser.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPServedUser")
#ifdef RESTRICT_AndroidGovNistJavaxSipHeaderImsPServedUser
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPServedUser 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPServedUser 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSipHeaderImsPServedUser

#if !defined (AndroidGovNistJavaxSipHeaderImsPServedUser_) && (INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPServedUser || defined(INCLUDE_AndroidGovNistJavaxSipHeaderImsPServedUser))
#define AndroidGovNistJavaxSipHeaderImsPServedUser_

#define RESTRICT_AndroidGovNistJavaxSipHeaderAddressParametersHeader 1
#define INCLUDE_AndroidGovNistJavaxSipHeaderAddressParametersHeader 1
#include "android/gov/nist/javax/sip/header/AddressParametersHeader.h"

#define RESTRICT_AndroidGovNistJavaxSipHeaderImsPServedUserHeader 1
#define INCLUDE_AndroidGovNistJavaxSipHeaderImsPServedUserHeader 1
#include "android/gov/nist/javax/sip/header/ims/PServedUserHeader.h"

#define RESTRICT_AndroidGovNistJavaxSipHeaderImsSIPHeaderNamesIms 1
#define INCLUDE_AndroidGovNistJavaxSipHeaderImsSIPHeaderNamesIms 1
#include "android/gov/nist/javax/sip/header/ims/SIPHeaderNamesIms.h"

#define RESTRICT_AndroidJavaxSipHeaderExtensionHeader 1
#define INCLUDE_AndroidJavaxSipHeaderExtensionHeader 1
#include "android/javax/sip/header/ExtensionHeader.h"

@class AndroidGovNistJavaxSipAddressAddressImpl;
@class JavaLangStringBuilder;

@interface AndroidGovNistJavaxSipHeaderImsPServedUser : AndroidGovNistJavaxSipHeaderAddressParametersHeader < AndroidGovNistJavaxSipHeaderImsPServedUserHeader, AndroidGovNistJavaxSipHeaderImsSIPHeaderNamesIms, AndroidJavaxSipHeaderExtensionHeader >

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithAndroidGovNistJavaxSipAddressAddressImpl:(AndroidGovNistJavaxSipAddressAddressImpl *)address;

- (id)java_clone;

- (jboolean)isEqual:(id)other;

- (NSString *)getRegistrationState;

- (NSString *)getSessionCase;

- (void)setRegistrationStateWithNSString:(NSString *)registrationState;

- (void)setSessionCaseWithNSString:(NSString *)sessionCase;

- (void)setValueWithNSString:(NSString *)value;

#pragma mark Protected

- (JavaLangStringBuilder *)encodeBodyWithJavaLangStringBuilder:(JavaLangStringBuilder *)retval;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSipHeaderImsPServedUser)

FOUNDATION_EXPORT void AndroidGovNistJavaxSipHeaderImsPServedUser_initWithAndroidGovNistJavaxSipAddressAddressImpl_(AndroidGovNistJavaxSipHeaderImsPServedUser *self, AndroidGovNistJavaxSipAddressAddressImpl *address);

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderImsPServedUser *new_AndroidGovNistJavaxSipHeaderImsPServedUser_initWithAndroidGovNistJavaxSipAddressAddressImpl_(AndroidGovNistJavaxSipAddressAddressImpl *address) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderImsPServedUser *create_AndroidGovNistJavaxSipHeaderImsPServedUser_initWithAndroidGovNistJavaxSipAddressAddressImpl_(AndroidGovNistJavaxSipAddressAddressImpl *address);

FOUNDATION_EXPORT void AndroidGovNistJavaxSipHeaderImsPServedUser_init(AndroidGovNistJavaxSipHeaderImsPServedUser *self);

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderImsPServedUser *new_AndroidGovNistJavaxSipHeaderImsPServedUser_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderImsPServedUser *create_AndroidGovNistJavaxSipHeaderImsPServedUser_init();

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSipHeaderImsPServedUser)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPServedUser")
