//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/header/ims/PVisitedNetworkID.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID")
#ifdef RESTRICT_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID

#if !defined (AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID_) && (INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID || defined(INCLUDE_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID))
#define AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID_

#define RESTRICT_AndroidGovNistJavaxSipHeaderParametersHeader 1
#define INCLUDE_AndroidGovNistJavaxSipHeaderParametersHeader 1
#include "android/gov/nist/javax/sip/header/ParametersHeader.h"

#define RESTRICT_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDHeader 1
#define INCLUDE_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDHeader 1
#include "android/gov/nist/javax/sip/header/ims/PVisitedNetworkIDHeader.h"

#define RESTRICT_AndroidGovNistJavaxSipHeaderImsSIPHeaderNamesIms 1
#define INCLUDE_AndroidGovNistJavaxSipHeaderImsSIPHeaderNamesIms 1
#include "android/gov/nist/javax/sip/header/ims/SIPHeaderNamesIms.h"

#define RESTRICT_AndroidJavaxSipHeaderExtensionHeader 1
#define INCLUDE_AndroidJavaxSipHeaderExtensionHeader 1
#include "android/javax/sip/header/ExtensionHeader.h"

@class AndroidGovNistCoreToken;
@class JavaLangStringBuilder;

@interface AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID : AndroidGovNistJavaxSipHeaderParametersHeader < AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDHeader, AndroidGovNistJavaxSipHeaderImsSIPHeaderNamesIms, AndroidJavaxSipHeaderExtensionHeader >

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)networkID;

- (instancetype)initWithAndroidGovNistCoreToken:(AndroidGovNistCoreToken *)tok;

- (id)java_clone;

- (JavaLangStringBuilder *)encodeBodyWithJavaLangStringBuilder:(JavaLangStringBuilder *)retval;

- (jboolean)isEqual:(id)other;

- (NSString *)getVisitedNetworkID;

- (void)setValueWithNSString:(NSString *)value;

- (void)setVisitedNetworkIDWithNSString:(NSString *)networkID;

- (void)setVisitedNetworkIDWithAndroidGovNistCoreToken:(AndroidGovNistCoreToken *)networkID;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID)

FOUNDATION_EXPORT void AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID_init(AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID *self);

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID *new_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID *create_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID_init();

FOUNDATION_EXPORT void AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID_initWithNSString_(AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID *self, NSString *networkID);

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID *new_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID_initWithNSString_(NSString *networkID) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID *create_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID_initWithNSString_(NSString *networkID);

FOUNDATION_EXPORT void AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID_initWithAndroidGovNistCoreToken_(AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID *self, AndroidGovNistCoreToken *tok);

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID *new_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID_initWithAndroidGovNistCoreToken_(AndroidGovNistCoreToken *tok) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID *create_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID_initWithAndroidGovNistCoreToken_(AndroidGovNistCoreToken *tok);

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID")
