//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/header/ims/PVisitedNetworkIDList.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDList")
#ifdef RESTRICT_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDList
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDList 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDList 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDList

#if !defined (AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDList_) && (INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDList || defined(INCLUDE_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDList))
#define AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDList_

#define RESTRICT_AndroidGovNistJavaxSipHeaderSIPHeaderList 1
#define INCLUDE_AndroidGovNistJavaxSipHeaderSIPHeaderList 1
#include "android/gov/nist/javax/sip/header/SIPHeaderList.h"

@class AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID;

@interface AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDList : AndroidGovNistJavaxSipHeaderSIPHeaderList

#pragma mark Public

- (instancetype)init;

- (id)java_clone;

- (AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID *)getWithInt:(jint)arg0;

- (AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID *)removeWithInt:(jint)arg0;

- (AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID *)setWithInt:(jint)arg0
                                                          withId:(AndroidGovNistJavaxSipHeaderImsPVisitedNetworkID *)arg1;

#pragma mark Package-Private

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDList)

FOUNDATION_EXPORT void AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDList_init(AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDList *self);

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDList *new_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDList_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDList *create_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDList_init();

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDList)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsPVisitedNetworkIDList")
