//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/header/ims/SecurityAgreeHeader.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsSecurityAgreeHeader")
#ifdef RESTRICT_AndroidGovNistJavaxSipHeaderImsSecurityAgreeHeader
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsSecurityAgreeHeader 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsSecurityAgreeHeader 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSipHeaderImsSecurityAgreeHeader

#if !defined (AndroidGovNistJavaxSipHeaderImsSecurityAgreeHeader_) && (INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsSecurityAgreeHeader || defined(INCLUDE_AndroidGovNistJavaxSipHeaderImsSecurityAgreeHeader))
#define AndroidGovNistJavaxSipHeaderImsSecurityAgreeHeader_

#define RESTRICT_AndroidJavaxSipHeaderParameters 1
#define INCLUDE_AndroidJavaxSipHeaderParameters 1
#include "android/javax/sip/header/Parameters.h"

#define RESTRICT_AndroidJavaxSipHeaderHeader 1
#define INCLUDE_AndroidJavaxSipHeaderHeader 1
#include "android/javax/sip/header/Header.h"

@protocol AndroidGovNistJavaxSipHeaderImsSecurityAgreeHeader < AndroidJavaxSipHeaderParameters, AndroidJavaxSipHeaderHeader, JavaObject >

- (void)setSecurityMechanismWithNSString:(NSString *)secMech;

- (void)setEncryptionAlgorithmWithNSString:(NSString *)ealg;

- (void)setAlgorithmWithNSString:(NSString *)alg;

- (void)setProtocolWithNSString:(NSString *)prot;

- (void)setModeWithNSString:(NSString *)mod;

- (void)setSPIClientWithInt:(jint)spic;

- (void)setSPIServerWithInt:(jint)spis;

- (void)setPortClientWithInt:(jint)portC;

- (void)setPortServerWithInt:(jint)portS;

- (void)setPreferenceWithFloat:(jfloat)q;

- (NSString *)getSecurityMechanism;

- (NSString *)getEncryptionAlgorithm;

- (NSString *)getAlgorithm;

- (NSString *)getProtocol;

- (NSString *)getMode;

- (jint)getSPIClient;

- (jint)getSPIServer;

- (jint)getPortClient;

- (jint)getPortServer;

- (jfloat)getPreference;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSipHeaderImsSecurityAgreeHeader)

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSipHeaderImsSecurityAgreeHeader)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSipHeaderImsSecurityAgreeHeader")
