//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sdp/fields/Indentation.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSdpFieldsIndentation")
#ifdef RESTRICT_AndroidGovNistJavaxSdpFieldsIndentation
#define INCLUDE_ALL_AndroidGovNistJavaxSdpFieldsIndentation 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSdpFieldsIndentation 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSdpFieldsIndentation

#if !defined (AndroidGovNistJavaxSdpFieldsIndentation_) && (INCLUDE_ALL_AndroidGovNistJavaxSdpFieldsIndentation || defined(INCLUDE_AndroidGovNistJavaxSdpFieldsIndentation))
#define AndroidGovNistJavaxSdpFieldsIndentation_

@interface AndroidGovNistJavaxSdpFieldsIndentation : NSObject

#pragma mark Protected

- (instancetype)init;

- (instancetype)initWithInt:(jint)initval;

- (void)decrement;

- (jint)getCount;

- (NSString *)getIndentation;

- (void)increment;

- (void)setIndentationWithInt:(jint)initval;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSdpFieldsIndentation)

FOUNDATION_EXPORT void AndroidGovNistJavaxSdpFieldsIndentation_init(AndroidGovNistJavaxSdpFieldsIndentation *self);

FOUNDATION_EXPORT AndroidGovNistJavaxSdpFieldsIndentation *new_AndroidGovNistJavaxSdpFieldsIndentation_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSdpFieldsIndentation *create_AndroidGovNistJavaxSdpFieldsIndentation_init();

FOUNDATION_EXPORT void AndroidGovNistJavaxSdpFieldsIndentation_initWithInt_(AndroidGovNistJavaxSdpFieldsIndentation *self, jint initval);

FOUNDATION_EXPORT AndroidGovNistJavaxSdpFieldsIndentation *new_AndroidGovNistJavaxSdpFieldsIndentation_initWithInt_(jint initval) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSdpFieldsIndentation *create_AndroidGovNistJavaxSdpFieldsIndentation_initWithInt_(jint initval);

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSdpFieldsIndentation)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSdpFieldsIndentation")
