//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sdp/fields/SDPObjectList.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "android/gov/nist/core/GenericObject.h"
#include "android/gov/nist/core/GenericObjectList.h"
#include "android/gov/nist/javax/sdp/fields/SDPObject.h"
#include "android/gov/nist/javax/sdp/fields/SDPObjectList.h"
#include "java/lang/StringBuilder.h"
#include "java/util/Iterator.h"
#include "java/util/ListIterator.h"

#pragma clang diagnostic ignored "-Wincomplete-implementation"

NSString *AndroidGovNistJavaxSdpFieldsSDPObjectList_SDPFIELDS_PACKAGE = @"android.gov.nist.javax.sdp.fields";

@implementation AndroidGovNistJavaxSdpFieldsSDPObjectList

- (void)mergeObjectsWithAndroidGovNistCoreGenericObjectList:(AndroidGovNistCoreGenericObjectList *)mergeList {
  id<JavaUtilIterator> it1 = [self listIterator];
  id<JavaUtilIterator> it2 = [((AndroidGovNistCoreGenericObjectList *) nil_chk(mergeList)) listIterator];
  while ([((id<JavaUtilIterator>) nil_chk(it1)) hasNext]) {
    AndroidGovNistCoreGenericObject *outerObj = [it1 next];
    while ([((id<JavaUtilIterator>) nil_chk(it2)) hasNext]) {
      id innerObj = [it2 next];
      [((AndroidGovNistCoreGenericObject *) nil_chk(outerObj)) mergeWithId:innerObj];
    }
  }
}

- (void)addWithAndroidGovNistJavaxSdpFieldsSDPObject:(AndroidGovNistJavaxSdpFieldsSDPObject *)s {
  [super addWithId:s];
}

- (instancetype)initWithNSString:(NSString *)lname
                    withNSString:(NSString *)classname {
  AndroidGovNistJavaxSdpFieldsSDPObjectList_initWithNSString_withNSString_(self, lname, classname);
  return self;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  AndroidGovNistJavaxSdpFieldsSDPObjectList_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)lname {
  AndroidGovNistJavaxSdpFieldsSDPObjectList_initWithNSString_(self, lname);
  return self;
}

- (AndroidGovNistCoreGenericObject *)first {
  return (AndroidGovNistJavaxSdpFieldsSDPObject *) cast_chk([super first], [AndroidGovNistJavaxSdpFieldsSDPObject class]);
}

- (AndroidGovNistCoreGenericObject *)next {
  return (AndroidGovNistJavaxSdpFieldsSDPObject *) cast_chk([super next], [AndroidGovNistJavaxSdpFieldsSDPObject class]);
}

- (NSString *)encode {
  JavaLangStringBuilder *retval = create_JavaLangStringBuilder_init();
  AndroidGovNistJavaxSdpFieldsSDPObject *sdpObject;
  for (sdpObject = (AndroidGovNistJavaxSdpFieldsSDPObject *) cast_chk([self first], [AndroidGovNistJavaxSdpFieldsSDPObject class]); sdpObject != nil; sdpObject = (AndroidGovNistJavaxSdpFieldsSDPObject *) cast_chk([self next], [AndroidGovNistJavaxSdpFieldsSDPObject class])) {
    [retval appendWithNSString:[sdpObject encode]];
  }
  return [retval description];
}

- (NSString *)description {
  return [self encode];
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf, len);
}

- (void)dealloc {
  JreCheckFinalize(self, [AndroidGovNistJavaxSdpFieldsSDPObjectList class]);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 4, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 5, -1, -1, -1, -1 },
    { NULL, "LAndroidGovNistCoreGenericObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LAndroidGovNistCoreGenericObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 6, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(mergeObjectsWithAndroidGovNistCoreGenericObjectList:);
  methods[1].selector = @selector(addWithAndroidGovNistJavaxSdpFieldsSDPObject:);
  methods[2].selector = @selector(initWithNSString:withNSString:);
  methods[3].selector = @selector(init);
  methods[4].selector = @selector(initWithNSString:);
  methods[5].selector = @selector(first);
  methods[6].selector = @selector(next);
  methods[7].selector = @selector(encode);
  methods[8].selector = @selector(description);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "SDPFIELDS_PACKAGE", "LNSString;", .constantValue.asLong = 0, 0x1c, -1, 7, -1, -1 },
  };
  static const void *ptrTable[] = { "mergeObjects", "LAndroidGovNistCoreGenericObjectList;", "add", "LAndroidGovNistJavaxSdpFieldsSDPObject;", "LNSString;LNSString;", "LNSString;", "toString", &AndroidGovNistJavaxSdpFieldsSDPObjectList_SDPFIELDS_PACKAGE };
  static const J2ObjcClassInfo _AndroidGovNistJavaxSdpFieldsSDPObjectList = { "SDPObjectList", "android.gov.nist.javax.sdp.fields", ptrTable, methods, fields, 7, 0x1, 9, 1, -1, -1, -1, -1, -1 };
  return &_AndroidGovNistJavaxSdpFieldsSDPObjectList;
}

@end

void AndroidGovNistJavaxSdpFieldsSDPObjectList_initWithNSString_withNSString_(AndroidGovNistJavaxSdpFieldsSDPObjectList *self, NSString *lname, NSString *classname) {
  AndroidGovNistCoreGenericObjectList_initWithNSString_withNSString_(self, lname, classname);
}

AndroidGovNistJavaxSdpFieldsSDPObjectList *new_AndroidGovNistJavaxSdpFieldsSDPObjectList_initWithNSString_withNSString_(NSString *lname, NSString *classname) {
  J2OBJC_NEW_IMPL(AndroidGovNistJavaxSdpFieldsSDPObjectList, initWithNSString_withNSString_, lname, classname)
}

AndroidGovNistJavaxSdpFieldsSDPObjectList *create_AndroidGovNistJavaxSdpFieldsSDPObjectList_initWithNSString_withNSString_(NSString *lname, NSString *classname) {
  J2OBJC_CREATE_IMPL(AndroidGovNistJavaxSdpFieldsSDPObjectList, initWithNSString_withNSString_, lname, classname)
}

void AndroidGovNistJavaxSdpFieldsSDPObjectList_init(AndroidGovNistJavaxSdpFieldsSDPObjectList *self) {
  AndroidGovNistCoreGenericObjectList_initWithNSString_withIOSClass_(self, nil, AndroidGovNistJavaxSdpFieldsSDPObject_class_());
}

AndroidGovNistJavaxSdpFieldsSDPObjectList *new_AndroidGovNistJavaxSdpFieldsSDPObjectList_init() {
  J2OBJC_NEW_IMPL(AndroidGovNistJavaxSdpFieldsSDPObjectList, init)
}

AndroidGovNistJavaxSdpFieldsSDPObjectList *create_AndroidGovNistJavaxSdpFieldsSDPObjectList_init() {
  J2OBJC_CREATE_IMPL(AndroidGovNistJavaxSdpFieldsSDPObjectList, init)
}

void AndroidGovNistJavaxSdpFieldsSDPObjectList_initWithNSString_(AndroidGovNistJavaxSdpFieldsSDPObjectList *self, NSString *lname) {
  AndroidGovNistCoreGenericObjectList_initWithNSString_withNSString_(self, lname, JreStrcat("$$", AndroidGovNistJavaxSdpFieldsSDPObjectList_SDPFIELDS_PACKAGE, @".SDPObject"));
}

AndroidGovNistJavaxSdpFieldsSDPObjectList *new_AndroidGovNistJavaxSdpFieldsSDPObjectList_initWithNSString_(NSString *lname) {
  J2OBJC_NEW_IMPL(AndroidGovNistJavaxSdpFieldsSDPObjectList, initWithNSString_, lname)
}

AndroidGovNistJavaxSdpFieldsSDPObjectList *create_AndroidGovNistJavaxSdpFieldsSDPObjectList_initWithNSString_(NSString *lname) {
  J2OBJC_CREATE_IMPL(AndroidGovNistJavaxSdpFieldsSDPObjectList, initWithNSString_, lname)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AndroidGovNistJavaxSdpFieldsSDPObjectList)
