//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/javax/sdp/Key.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidJavaxSdpKey")
#ifdef RESTRICT_AndroidJavaxSdpKey
#define INCLUDE_ALL_AndroidJavaxSdpKey 0
#else
#define INCLUDE_ALL_AndroidJavaxSdpKey 1
#endif
#undef RESTRICT_AndroidJavaxSdpKey

#if !defined (AndroidJavaxSdpKey_) && (INCLUDE_ALL_AndroidJavaxSdpKey || defined(INCLUDE_AndroidJavaxSdpKey))
#define AndroidJavaxSdpKey_

#define RESTRICT_AndroidJavaxSdpField 1
#define INCLUDE_AndroidJavaxSdpField 1
#include "android/javax/sdp/Field.h"

@protocol AndroidJavaxSdpKey < AndroidJavaxSdpField, JavaObject >

- (NSString *)getMethod;

- (void)setMethodWithNSString:(NSString *)name;

- (jboolean)hasKey;

- (NSString *)getKey;

- (void)setKeyWithNSString:(NSString *)key;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidJavaxSdpKey)

J2OBJC_TYPE_LITERAL_HEADER(AndroidJavaxSdpKey)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidJavaxSdpKey")
