//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/javax/sdp/TimeDescription.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidJavaxSdpTimeDescription")
#ifdef RESTRICT_AndroidJavaxSdpTimeDescription
#define INCLUDE_ALL_AndroidJavaxSdpTimeDescription 0
#else
#define INCLUDE_ALL_AndroidJavaxSdpTimeDescription 1
#endif
#undef RESTRICT_AndroidJavaxSdpTimeDescription

#if !defined (AndroidJavaxSdpTimeDescription_) && (INCLUDE_ALL_AndroidJavaxSdpTimeDescription || defined(INCLUDE_AndroidJavaxSdpTimeDescription))
#define AndroidJavaxSdpTimeDescription_

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@class JavaUtilVector;
@protocol AndroidJavaxSdpTime;

@protocol AndroidJavaxSdpTimeDescription < JavaIoSerializable, NSCopying, JavaObject >

- (id<AndroidJavaxSdpTime>)getTime;

- (void)setTimeWithAndroidJavaxSdpTime:(id<AndroidJavaxSdpTime>)t;

- (JavaUtilVector *)getRepeatTimesWithBoolean:(jboolean)create;

- (void)setRepeatTimesWithJavaUtilVector:(JavaUtilVector *)repeatTimes;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidJavaxSdpTimeDescription)

inline jlong AndroidJavaxSdpTimeDescription_get_NTP_CONST();
#define AndroidJavaxSdpTimeDescription_NTP_CONST 2208988800LL
J2OBJC_STATIC_FIELD_CONSTANT(AndroidJavaxSdpTimeDescription, NTP_CONST, jlong)

J2OBJC_TYPE_LITERAL_HEADER(AndroidJavaxSdpTimeDescription)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidJavaxSdpTimeDescription")
