//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/DefaultAddressResolver.java
//

#include "J2ObjC_source.h"
#include "android/gov/nist/javax/sip/DefaultAddressResolver.h"
#include "android/gov/nist/javax/sip/stack/HopImpl.h"
#include "android/gov/nist/javax/sip/stack/MessageProcessor.h"
#include "android/javax/sip/address/Hop.h"

@implementation AndroidGovNistJavaxSipDefaultAddressResolver

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  AndroidGovNistJavaxSipDefaultAddressResolver_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (id<AndroidJavaxSipAddressHop>)resolveAddressWithAndroidJavaxSipAddressHop:(id<AndroidJavaxSipAddressHop>)inputAddress {
  if ([((id<AndroidJavaxSipAddressHop>) nil_chk(inputAddress)) getPort] != -1) return inputAddress;
  else {
    return create_AndroidGovNistJavaxSipStackHopImpl_initWithNSString_withInt_withNSString_([inputAddress getHost], AndroidGovNistJavaxSipStackMessageProcessor_getDefaultPortWithNSString_([inputAddress getTransport]), [inputAddress getTransport]);
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LAndroidJavaxSipAddressHop;", 0x1, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(resolveAddressWithAndroidJavaxSipAddressHop:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "resolveAddress", "LAndroidJavaxSipAddressHop;" };
  static const J2ObjcClassInfo _AndroidGovNistJavaxSipDefaultAddressResolver = { "DefaultAddressResolver", "android.gov.nist.javax.sip", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_AndroidGovNistJavaxSipDefaultAddressResolver;
}

@end

void AndroidGovNistJavaxSipDefaultAddressResolver_init(AndroidGovNistJavaxSipDefaultAddressResolver *self) {
  NSObject_init(self);
}

AndroidGovNistJavaxSipDefaultAddressResolver *new_AndroidGovNistJavaxSipDefaultAddressResolver_init() {
  J2OBJC_NEW_IMPL(AndroidGovNistJavaxSipDefaultAddressResolver, init)
}

AndroidGovNistJavaxSipDefaultAddressResolver *create_AndroidGovNistJavaxSipDefaultAddressResolver_init() {
  J2OBJC_CREATE_IMPL(AndroidGovNistJavaxSipDefaultAddressResolver, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AndroidGovNistJavaxSipDefaultAddressResolver)
