//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/RequestEventExt.java
//

#include "J2ObjC_source.h"
#include "android/gov/nist/javax/sip/RequestEventExt.h"
#include "android/javax/sip/Dialog.h"
#include "android/javax/sip/RequestEvent.h"
#include "android/javax/sip/ServerTransaction.h"
#include "android/javax/sip/message/Request.h"

@interface AndroidGovNistJavaxSipRequestEventExt () {
 @public
  NSString *remoteIpAddress_;
  jint remotePort_;
}

@end

J2OBJC_FIELD_SETTER(AndroidGovNistJavaxSipRequestEventExt, remoteIpAddress_, NSString *)

@implementation AndroidGovNistJavaxSipRequestEventExt

- (instancetype)initWithId:(id)source
withAndroidJavaxSipServerTransaction:(id<AndroidJavaxSipServerTransaction>)serverTransaction
 withAndroidJavaxSipDialog:(id<AndroidJavaxSipDialog>)dialog
withAndroidJavaxSipMessageRequest:(id<AndroidJavaxSipMessageRequest>)request {
  AndroidGovNistJavaxSipRequestEventExt_initWithId_withAndroidJavaxSipServerTransaction_withAndroidJavaxSipDialog_withAndroidJavaxSipMessageRequest_(self, source, serverTransaction, dialog, request);
  return self;
}

- (void)setRemoteIpAddressWithNSString:(NSString *)remoteIpAddress {
  JreStrongAssign(&self->remoteIpAddress_, remoteIpAddress);
}

- (NSString *)getRemoteIpAddress {
  return remoteIpAddress_;
}

- (void)setRemotePortWithInt:(jint)remotePort {
  self->remotePort_ = remotePort;
}

- (jint)getRemotePort {
  return remotePort_;
}

- (void)dealloc {
  RELEASE_(remoteIpAddress_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithId:withAndroidJavaxSipServerTransaction:withAndroidJavaxSipDialog:withAndroidJavaxSipMessageRequest:);
  methods[1].selector = @selector(setRemoteIpAddressWithNSString:);
  methods[2].selector = @selector(getRemoteIpAddress);
  methods[3].selector = @selector(setRemotePortWithInt:);
  methods[4].selector = @selector(getRemotePort);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "remoteIpAddress_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "remotePort_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSObject;LAndroidJavaxSipServerTransaction;LAndroidJavaxSipDialog;LAndroidJavaxSipMessageRequest;", "setRemoteIpAddress", "LNSString;", "setRemotePort", "I" };
  static const J2ObjcClassInfo _AndroidGovNistJavaxSipRequestEventExt = { "RequestEventExt", "android.gov.nist.javax.sip", ptrTable, methods, fields, 7, 0x1, 5, 2, -1, -1, -1, -1, -1 };
  return &_AndroidGovNistJavaxSipRequestEventExt;
}

@end

void AndroidGovNistJavaxSipRequestEventExt_initWithId_withAndroidJavaxSipServerTransaction_withAndroidJavaxSipDialog_withAndroidJavaxSipMessageRequest_(AndroidGovNistJavaxSipRequestEventExt *self, id source, id<AndroidJavaxSipServerTransaction> serverTransaction, id<AndroidJavaxSipDialog> dialog, id<AndroidJavaxSipMessageRequest> request) {
  AndroidJavaxSipRequestEvent_initWithId_withAndroidJavaxSipServerTransaction_withAndroidJavaxSipDialog_withAndroidJavaxSipMessageRequest_(self, source, serverTransaction, dialog, request);
}

AndroidGovNistJavaxSipRequestEventExt *new_AndroidGovNistJavaxSipRequestEventExt_initWithId_withAndroidJavaxSipServerTransaction_withAndroidJavaxSipDialog_withAndroidJavaxSipMessageRequest_(id source, id<AndroidJavaxSipServerTransaction> serverTransaction, id<AndroidJavaxSipDialog> dialog, id<AndroidJavaxSipMessageRequest> request) {
  J2OBJC_NEW_IMPL(AndroidGovNistJavaxSipRequestEventExt, initWithId_withAndroidJavaxSipServerTransaction_withAndroidJavaxSipDialog_withAndroidJavaxSipMessageRequest_, source, serverTransaction, dialog, request)
}

AndroidGovNistJavaxSipRequestEventExt *create_AndroidGovNistJavaxSipRequestEventExt_initWithId_withAndroidJavaxSipServerTransaction_withAndroidJavaxSipDialog_withAndroidJavaxSipMessageRequest_(id source, id<AndroidJavaxSipServerTransaction> serverTransaction, id<AndroidJavaxSipDialog> dialog, id<AndroidJavaxSipMessageRequest> request) {
  J2OBJC_CREATE_IMPL(AndroidGovNistJavaxSipRequestEventExt, initWithId_withAndroidJavaxSipServerTransaction_withAndroidJavaxSipDialog_withAndroidJavaxSipMessageRequest_, source, serverTransaction, dialog, request)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AndroidGovNistJavaxSipRequestEventExt)
