//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/javax/sip/RequestEventExt.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistJavaxSipRequestEventExt")
#ifdef RESTRICT_AndroidGovNistJavaxSipRequestEventExt
#define INCLUDE_ALL_AndroidGovNistJavaxSipRequestEventExt 0
#else
#define INCLUDE_ALL_AndroidGovNistJavaxSipRequestEventExt 1
#endif
#undef RESTRICT_AndroidGovNistJavaxSipRequestEventExt

#if !defined (AndroidGovNistJavaxSipRequestEventExt_) && (INCLUDE_ALL_AndroidGovNistJavaxSipRequestEventExt || defined(INCLUDE_AndroidGovNistJavaxSipRequestEventExt))
#define AndroidGovNistJavaxSipRequestEventExt_

#define RESTRICT_AndroidJavaxSipRequestEvent 1
#define INCLUDE_AndroidJavaxSipRequestEvent 1
#include "android/javax/sip/RequestEvent.h"

@protocol AndroidJavaxSipDialog;
@protocol AndroidJavaxSipMessageRequest;
@protocol AndroidJavaxSipServerTransaction;

@interface AndroidGovNistJavaxSipRequestEventExt : AndroidJavaxSipRequestEvent

#pragma mark Public

- (instancetype)initWithId:(id)source
withAndroidJavaxSipServerTransaction:(id<AndroidJavaxSipServerTransaction>)serverTransaction
 withAndroidJavaxSipDialog:(id<AndroidJavaxSipDialog>)dialog
withAndroidJavaxSipMessageRequest:(id<AndroidJavaxSipMessageRequest>)request;

- (NSString *)getRemoteIpAddress;

- (jint)getRemotePort;

- (void)setRemoteIpAddressWithNSString:(NSString *)remoteIpAddress;

- (void)setRemotePortWithInt:(jint)remotePort;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistJavaxSipRequestEventExt)

FOUNDATION_EXPORT void AndroidGovNistJavaxSipRequestEventExt_initWithId_withAndroidJavaxSipServerTransaction_withAndroidJavaxSipDialog_withAndroidJavaxSipMessageRequest_(AndroidGovNistJavaxSipRequestEventExt *self, id source, id<AndroidJavaxSipServerTransaction> serverTransaction, id<AndroidJavaxSipDialog> dialog, id<AndroidJavaxSipMessageRequest> request);

FOUNDATION_EXPORT AndroidGovNistJavaxSipRequestEventExt *new_AndroidGovNistJavaxSipRequestEventExt_initWithId_withAndroidJavaxSipServerTransaction_withAndroidJavaxSipDialog_withAndroidJavaxSipMessageRequest_(id source, id<AndroidJavaxSipServerTransaction> serverTransaction, id<AndroidJavaxSipDialog> dialog, id<AndroidJavaxSipMessageRequest> request) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistJavaxSipRequestEventExt *create_AndroidGovNistJavaxSipRequestEventExt_initWithId_withAndroidJavaxSipServerTransaction_withAndroidJavaxSipDialog_withAndroidJavaxSipMessageRequest_(id source, id<AndroidJavaxSipServerTransaction> serverTransaction, id<AndroidJavaxSipDialog> dialog, id<AndroidJavaxSipMessageRequest> request);

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistJavaxSipRequestEventExt)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistJavaxSipRequestEventExt")
