//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/javax/sip/message/Request.java
//

#include "J2ObjC_source.h"
#include "android/javax/sip/message/Request.h"

@interface AndroidJavaxSipMessageRequest : NSObject

@end

NSString *AndroidJavaxSipMessageRequest_ACK = @"ACK";
NSString *AndroidJavaxSipMessageRequest_BYE = @"BYE";
NSString *AndroidJavaxSipMessageRequest_CANCEL = @"CANCEL";
NSString *AndroidJavaxSipMessageRequest_INVITE = @"INVITE";
NSString *AndroidJavaxSipMessageRequest_OPTIONS = @"OPTIONS";
NSString *AndroidJavaxSipMessageRequest_REGISTER = @"REGISTER";
NSString *AndroidJavaxSipMessageRequest_NOTIFY = @"NOTIFY";
NSString *AndroidJavaxSipMessageRequest_SUBSCRIBE = @"SUBSCRIBE";
NSString *AndroidJavaxSipMessageRequest_MESSAGE = @"MESSAGE";
NSString *AndroidJavaxSipMessageRequest_REFER = @"REFER";
NSString *AndroidJavaxSipMessageRequest_INFO = @"INFO";
NSString *AndroidJavaxSipMessageRequest_PRACK = @"PRACK";
NSString *AndroidJavaxSipMessageRequest_UPDATE = @"UPDATE";
NSString *AndroidJavaxSipMessageRequest_PUBLISH = @"PUBLISH";

@implementation AndroidJavaxSipMessageRequest

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 0, 1, 2, -1, -1, -1 },
    { NULL, "LAndroidJavaxSipAddressURI;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 3, 4, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getMethod);
  methods[1].selector = @selector(setMethodWithNSString:);
  methods[2].selector = @selector(getRequestURI);
  methods[3].selector = @selector(setRequestURIWithAndroidJavaxSipAddressURI:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "ACK", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 5, -1, -1 },
    { "BYE", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 6, -1, -1 },
    { "CANCEL", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 7, -1, -1 },
    { "INVITE", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 8, -1, -1 },
    { "OPTIONS", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 9, -1, -1 },
    { "REGISTER", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 10, -1, -1 },
    { "NOTIFY", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 11, -1, -1 },
    { "SUBSCRIBE", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 12, -1, -1 },
    { "MESSAGE", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 13, -1, -1 },
    { "REFER", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 14, -1, -1 },
    { "INFO", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 15, -1, -1 },
    { "PRACK", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 16, -1, -1 },
    { "UPDATE", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 17, -1, -1 },
    { "PUBLISH", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 18, -1, -1 },
  };
  static const void *ptrTable[] = { "setMethod", "LNSString;", "LJavaTextParseException;", "setRequestURI", "LAndroidJavaxSipAddressURI;", &AndroidJavaxSipMessageRequest_ACK, &AndroidJavaxSipMessageRequest_BYE, &AndroidJavaxSipMessageRequest_CANCEL, &AndroidJavaxSipMessageRequest_INVITE, &AndroidJavaxSipMessageRequest_OPTIONS, &AndroidJavaxSipMessageRequest_REGISTER, &AndroidJavaxSipMessageRequest_NOTIFY, &AndroidJavaxSipMessageRequest_SUBSCRIBE, &AndroidJavaxSipMessageRequest_MESSAGE, &AndroidJavaxSipMessageRequest_REFER, &AndroidJavaxSipMessageRequest_INFO, &AndroidJavaxSipMessageRequest_PRACK, &AndroidJavaxSipMessageRequest_UPDATE, &AndroidJavaxSipMessageRequest_PUBLISH };
  static const J2ObjcClassInfo _AndroidJavaxSipMessageRequest = { "Request", "android.javax.sip.message", ptrTable, methods, fields, 7, 0x609, 4, 14, -1, -1, -1, -1, -1 };
  return &_AndroidJavaxSipMessageRequest;
}

- (id)copyWithZone:(NSZone *)zone {
  return [[self java_clone] retain];
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(AndroidJavaxSipMessageRequest)
