//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/android/gov/nist/core/NameValueList.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidGovNistCoreNameValueList")
#ifdef RESTRICT_AndroidGovNistCoreNameValueList
#define INCLUDE_ALL_AndroidGovNistCoreNameValueList 0
#else
#define INCLUDE_ALL_AndroidGovNistCoreNameValueList 1
#endif
#undef RESTRICT_AndroidGovNistCoreNameValueList

#if !defined (AndroidGovNistCoreNameValueList_) && (INCLUDE_ALL_AndroidGovNistCoreNameValueList || defined(INCLUDE_AndroidGovNistCoreNameValueList))
#define AndroidGovNistCoreNameValueList_

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

#define RESTRICT_JavaUtilMap 1
#define INCLUDE_JavaUtilMap 1
#include "java/util/Map.h"

@class AndroidGovNistCoreNameValue;
@class JavaLangStringBuilder;
@protocol JavaUtilCollection;
@protocol JavaUtilFunctionBiConsumer;
@protocol JavaUtilFunctionBiFunction;
@protocol JavaUtilFunctionFunction;
@protocol JavaUtilIterator;
@protocol JavaUtilSet;

@interface AndroidGovNistCoreNameValueList : NSObject < JavaIoSerializable, NSCopying, JavaUtilMap >

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithBoolean:(jboolean)sync;

- (void)clear;

- (id)java_clone;

- (AndroidGovNistCoreNameValue *)computeIfAbsentWithId:(NSString *)arg0
                          withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg1;

- (AndroidGovNistCoreNameValue *)computeIfPresentWithId:(NSString *)arg0
                         withJavaUtilFunctionBiFunction:(id<JavaUtilFunctionBiFunction>)arg1;

- (AndroidGovNistCoreNameValue *)computeWithId:(NSString *)arg0
                withJavaUtilFunctionBiFunction:(id<JavaUtilFunctionBiFunction>)arg1;

- (jboolean)containsKeyWithId:(id)key;

- (jboolean)containsValueWithId:(id)value;

- (jboolean)delete__WithNSString:(NSString *)name;

- (NSString *)encode;

- (JavaLangStringBuilder *)encodeWithJavaLangStringBuilder:(JavaLangStringBuilder *)buffer;

- (id<JavaUtilSet>)entrySet;

- (jboolean)isEqual:(id)otherObject;

- (AndroidGovNistCoreNameValue *)getWithId:(id)key;

- (id<JavaUtilIterator>)getNames;

- (AndroidGovNistCoreNameValue *)getNameValueWithNSString:(NSString *)name;

- (AndroidGovNistCoreNameValue *)getOrDefaultWithId:(id)arg0
                                             withId:(AndroidGovNistCoreNameValue *)arg1;

- (NSString *)getParameterWithNSString:(NSString *)name;

- (NSString *)getParameterWithNSString:(NSString *)name
                           withBoolean:(jboolean)stripQuotes;

- (id)getValueWithNSString:(NSString *)name;

- (id)getValueWithNSString:(NSString *)name
               withBoolean:(jboolean)stripQuotes;

- (NSUInteger)hash;

- (jboolean)hasNameValueWithNSString:(NSString *)name;

- (jboolean)isEmpty;

- (id<JavaUtilIterator>)iterator;

- (id<JavaUtilSet>)keySet;

- (AndroidGovNistCoreNameValue *)mergeWithId:(NSString *)arg0
                                      withId:(AndroidGovNistCoreNameValue *)arg1
              withJavaUtilFunctionBiFunction:(id<JavaUtilFunctionBiFunction>)arg2;

- (AndroidGovNistCoreNameValue *)putWithId:(NSString *)name
                                    withId:(AndroidGovNistCoreNameValue *)nameValue;

- (void)putAllWithJavaUtilMap:(id<JavaUtilMap>)map;

- (AndroidGovNistCoreNameValue *)putIfAbsentWithId:(NSString *)arg0
                                            withId:(AndroidGovNistCoreNameValue *)arg1;

- (AndroidGovNistCoreNameValue *)removeWithId:(id)key;

- (AndroidGovNistCoreNameValue *)replaceWithId:(NSString *)arg0
                                        withId:(AndroidGovNistCoreNameValue *)arg1;

- (void)setWithAndroidGovNistCoreNameValue:(AndroidGovNistCoreNameValue *)nv;

- (void)setWithNSString:(NSString *)name
                 withId:(id)value;

- (void)setSeparatorWithNSString:(NSString *)separator;

- (jint)size;

- (NSString *)description;

- (id<JavaUtilCollection>)values;

#pragma mark Protected

- (id<JavaUtilMap>)getMap;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidGovNistCoreNameValueList)

FOUNDATION_EXPORT void AndroidGovNistCoreNameValueList_init(AndroidGovNistCoreNameValueList *self);

FOUNDATION_EXPORT AndroidGovNistCoreNameValueList *new_AndroidGovNistCoreNameValueList_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistCoreNameValueList *create_AndroidGovNistCoreNameValueList_init();

FOUNDATION_EXPORT void AndroidGovNistCoreNameValueList_initWithBoolean_(AndroidGovNistCoreNameValueList *self, jboolean sync);

FOUNDATION_EXPORT AndroidGovNistCoreNameValueList *new_AndroidGovNistCoreNameValueList_initWithBoolean_(jboolean sync) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidGovNistCoreNameValueList *create_AndroidGovNistCoreNameValueList_initWithBoolean_(jboolean sync);

J2OBJC_TYPE_LITERAL_HEADER(AndroidGovNistCoreNameValueList)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidGovNistCoreNameValueList")
